/** `@bombfarm/hero/components` — the hero and roster React views. */
export { RosterSortHeader } from './hero-picker/roster-sort-header';
export type { RosterSortDir, RosterSortKey } from './hero-picker/roster-sort-header';
export { HeroPickerDialogView } from './hero-picker/hero-picker-dialog';
export type { HeroPickerActions, HeroPickerData } from './hero-picker/hero-picker-dialog';
export { HeroActiveToggle } from './hero-picker/hero-active-toggle';
export { PhasesHeroSwitcherView } from './phases-hero-switcher';
export type { HeroPickerSlot, HeroPickerSlotProps } from './phases-hero-switcher';
export { HeroCopyProvider, useHeroCopy } from './hero-copy-context';
export type { HeroCopyValue } from './hero-copy-context';
export { PhasesHeroPanel } from './phases-hero-panel';
export { HeroIdentityRollPanel } from './hero-identity-roll-panel';
export { HeroAbilitiesPanel } from './hero-abilities-panel';
export type { AbilityPanelEditing } from './hero-abilities-panel';
export { PhasesHeroFitTable } from './phases-hero-fit-table';
export { SheetTable } from './sheet-table';
export type { SheetTableInput } from './sheet-table';
export { PointsTable } from './points-table';
export type { PointsTableEditing } from './points-table';
export { PointsStatRow } from './points-stat-row';
export type { PointsStatRowValues } from './points-stat-row';
export { PointsResetAdvice } from './points-reset-advice';
export { PointsPreviewActions } from './points-preview-actions';
export type { OptimizeControl, PointsPreview } from './points-preview-actions';
export { PointsPreviewNotice } from './points-preview-notice';
export { LedgerBody } from './stat-breakdown-ledger';
export { FormulaBody } from './stat-breakdown-formula';
export { GearTab } from './gear-tab';
export type { GearEditing } from './gear-tab';
export { GearSlotsGrid } from './gear-slots-grid';
export type { GearSlotEditorSlot, GearSlotEditorSlotProps, SlotPatchHandler } from './gear-slots-grid';
export { GearSlotStatsGrid } from './gear-slot-stats-grid';
export { GearTotalsTable } from './gear-totals-table';
export { GearCompareSection } from './gear-compare-section';
export type { GearCompareEditing } from './gear-compare-section';
export { NextPointRanking, barPercent, fallbackNoteText, formatSignedGainPct } from './next-point-ranking';
export type { NextPointRankingInput } from './next-point-ranking';
