/**
 * Every player-facing string the farm screen prints, flat and typed. `as const` is load-bearing
 * twice over: it makes `FarmCopy` (`index.ts`) a mapped type over this exact key set, and it keeps
 * the values as string LITERALS, so a host app that spreads this object into a wider dictionary of
 * its own keeps the literal types it had before the strings moved here.
 */
export const farmEn = {
  phasesDifficultyLabel: "Difficulty",
  phasesMapLabel: "Map",
  phasesPhaseId: "Phase #{id}",
  phasesMapName: "Map name",
  phasesMapFacts: "Map",
  phasesEconomy: "Economy",
  phasesSpawnMix: "Prop mix",
  phasesColShare: "Share",
  phasesColGoldWiki: "Gold (wiki)",
  phasesColGoldActual: "Gold (yours)",
  phasesGateBadge: "Gate",
  phasesDifficulty: "Difficulty",
  phasesStoneHp: "Stone HP",
  phasesMitigation: "Mitigation",
  phasesPenNeedHint: "Need {pct}% pen to ignore all mitigation",
  phasesPropCount: "Props on map",
  phasesAvgPropHp: "Avg prop HP",
  phasesTotalMapHp: "Est. total map HP",
  phasesBossHp: "Boss / cage HP",
  phasesBossHint: "×10 stone — shared 2×2 pool",
  phasesBossGateHint: "Gate boss — clear before timer",
  phasesGateTimer: "Gate timer",
  phasesGateKey: "Key consumed",
  phasesItemDrops: "Item drops",
  phasesItemDropsValue: "Level {range} items",
  phasesXpPerProp: "XP per prop",
  phasesXpActualHint: "base value × your skill tree's XP multiplier",
  phasesGoldComum: "Gold (Common)",
  phasesGoldActualHint: "base value × (1 + your skill tree's team coin %)",
  phasesAvgGold: "Avg gold / prop",
  phasesMapGold: "Est. map gold",
  phasesJaulaSection: "Cage",
  phasesJaulaSectionDesc: "The cage runs on a logged-in play clock, not a per-room roll. It can arrive early — the chance climbs from 0 to the cap across the window — and is guaranteed at the end.",
  phasesJaulaEarly: "Early-arrival chance at this phase",
  phasesJaulaWindow: "Guarantee window",
  phasesJaulaWindowVip: "VIP {dur}",
  phasesJaulaHp: "Cage HP",
  phasesJaulaChest: "Hero chest odds",
  phasesDropsSection: "Drop chances",
  phasesDropChest: "Item chest",
  phasesDropKey: "Key",
  phasesDropTime: "Time chest",
  phasesDropGem: "Gem chest",
  phasesDropStone: "Stone chest",
  phasesDropActualHint: "base value + your skill tree's luck + your squad's average luck.",
  phasesDropsSectionDesc: "Which drops can roll depends on whether the phase is a gate.",
  phasesDropGateOnly: "Gates only",
  phasesDropNonGateOnly: "Non-gates only",
  phasesHeroSection: "Your hero",
  phasesHeroTip: "Uses your Account settings and each hero’s geared sheet + points.",
  phasesHeroPick: "Hero",
  phasesPenetration: "Penetration vs phase",
  phasesPenOk: "Fully piercing",
  phasesPenShort: "{gap}% short",
  phasesNormalHit: "Normal hit",
  phasesCritHit: "Critical hit",
  phasesAvgHit: "Avg hit (this build)",
  phasesFieldTime: "Field time",
  phasesColNormalHit: "Normal",
  phasesColCritHit: "Crit",
  phasesColFieldTime: "Field",
  phasesNoHeroes: "Import heroes in the Planner to see penetration and hits-to-kill here.",
  phasesNoHeroesLink: "import a save to unlock hero rows.",
  phasesSquadSection: "Top {slots} by solo DPS",
  phasesSquadTip: "Sum of the highest solo sustained-DPS builds in your roster (same Account), up to your casa slot count.",
  phasesSquadCombinedDps: "Combined sustained DPS",
  phasesClearEstimate: "Est. clear time",
  phasesClearDisclaimer: "The ranking board's model — your whole rotation under House and field limits, charging whole hits per prop. Not map HP ÷ combined DPS.",
  panelContext: "Context",
  phaseHint: "Insert phase number from {wiki}.",
  phaseHelp: "wiki",
  phaseHelpAria: "Bomb Farm wiki — phases",
  mitAutoHint: "from phase",
  phase: "Phase",
  mitPct: "Mit %",
  cycle: "Cycle",
  cycleSerial: "Serial",
  cycleWiki: "Wiki",
  walkS: "Walk s",
  extraDmg: "Extra dmg %",
  prop: "Target prop",
  contextTip: "Fuse {f}s · rest {r}m · stone HP {hp}",
  colProp: "Prop",
  colHp: "HP",
  colHits: "Hits",
  colNeed: "Need%",
  bossRow: "boss/cage",
  avgRow: "avg",

  // Farm Ranking board. The `phases*` keys above and the `farmRanking*`/`farmRespec*` keys below
  // share one file deliberately — they are one screen — and the prefixes keep each block greppable.
  farmRankingColPhase: "Phase",
  farmRankingColMitigation: "Mitigation",
  farmRankingColGold: "Gold",
  farmRankingColChests: "Item chest",
  farmRankingColKeys: "Key",
  farmRankingColGems: "Gem chest",
  farmRankingColTimePieces: "Time chest",
  farmRankingColXp: "XP",
  farmRankingColItemLevel: "Item level",
  farmRankingColClearTime: "Clear time",
  farmRankingColOneShot: "One-shot",

  farmRankingTitle: "Farm Ranking",
  farmRankingCaption: "Every wiki phase ranked by what it pays this account per hour",
  farmRankingEmptyNoRosterTitle: "No roster yet",
  farmRankingEmptyNoRosterDesc: "Add heroes in the Planner to rank phases for your account.",
  farmRankingEmptyNoHeroesTitle: "No heroes enabled",
  farmRankingEmptyNoHeroesDesc: "Enable at least one hero in the rotation pool below to see rates.",
  farmRankingEmptyComputeFailedTitle: "Could not compute the ranking",
  farmRankingEmptyComputeFailedDesc: "Something went wrong estimating rates for this account.",
  farmRankingEmptyNoMatchesTitle: "No phases match these filters",
  farmRankingEmptyNoMatchesDesc: "Clear a filter above to see more phases.",
  farmRankingFilterUnlockedLabel: "Unlocked only",
  farmRankingFilterUnlockedDisabledReason: "This filter needs a save with a known max phase.",
  farmRankingFilterAtoLabel: "Difficulty filter",
  farmRankingFilterAtoAll: "All difficulties",
  farmRankingFilterGateLabel: "Gate",
  farmRankingFilterGateAll: "All phases",
  farmRankingFilterGateOnly: "Gates only",
  farmRankingFilterGateNonGate: "Non-gates only",
  farmRankingFilterItemLevelLabel: "Min item level",
  farmRankingFilterItemLevelAll: "Any item level",
  farmRankingFilterItemLevelOption: "Level {level}+",
  farmRankingPoolLabel: "Rotation pool",
  farmRankingPoolHeroAria: "Include {name} in the farm estimate",
  farmRankingContentionTitle: "Your field is the bottleneck",
  farmRankingContentionTitleMaxSlots: "Your field is saturated",
  farmRankingContentionDesc:
    "{pct} of the time a rested hero waits on the bench because all {slots} of your field slots are taken. More field slots is the direct fix — the cap is {max}. The gold/hr estimate already charges this wait: it costs about {cost} of the rate you would get with room for everyone. Turning heroes off above lowers the waiting too, but usually lowers the total as well: a hero that only sometimes gets a slot still earns while it has one.",
  farmRankingContentionDescMaxSlots:
    "{pct} of the time a rested hero waits on the bench because all {slots} of your field slots are taken. {slots} is the maximum, so this one is structural — there are no more slots to buy. The gold/hr estimate already charges this wait: it costs about {cost} of the rate you would get with room for everyone. Turning heroes off above lowers the waiting too, but usually lowers the total as well: a hero that only sometimes gets a slot still earns while it has one.",
  farmRankingReturnBonusLabel: "Return Bonus",
  farmRankingReturnBonusOff: "Off",
  farmRankingReturnBonusOn: "On",
  farmRankingReturnBonusVip: "VIP",
  farmRankingGateBadge: "Gate",
  farmRankingOneShotYes: "Yes",
  farmRankingOneShotNo: "No",
  farmRankingOneShotTooltipYes: "Every enabled hero one-shots every prop type on this phase.",
  farmRankingOneShotTooltipNo: "Not every enabled hero one-shots every prop type — expected {htk} hits per prop.",
  farmRankingSortedBy: "Sorted by {column}, {direction}",
  farmRankingSortAsc: "ascending",
  farmRankingSortDesc: "descending",
  farmRankingCurrentPhase: "Current phase",

  // Farm Respec Advisor.
  farmRespecOptimize: "Optimize",
  farmRespecOptimizeBusy: "Calculating…",
  farmRespecHeadlineGain: "At least {pct}% more per hour",
  farmRespecGateFailed: "The quick check couldn't run this time. Optimize is still available for the full answer.",
  farmRespecPaybackHours: "Pays for itself in {hours} h",
  farmRespecPaybackNoChange: "Gold per hour does not change, so there is no gold payback to report.",
  farmRespecPanelHeading: "Respec advisor",
  farmRespecClose: "Close",
  farmRespecPanelGain: "{pct}% more per hour",
  farmRespecMetricGold: "Gold / hr",
  farmRespecMetricChests: "Chests / hr",
  farmRespecMetricPhase: "Phase",
  farmRespecMetricPhaseSame: "(same phase)",
  farmRespecMetricCost: "Respec cost",
  farmRespecMetricPayback: "Payback",
  farmRespecPaybackTip: "Payback divides the respec cost by the extra gold per hour the new build earns — the difference between the two Gold/hr numbers above, not the new rate on its own. If the proposed build earns less gold than today, or the same amount, there is no gold payback to report.",
  farmRespecBudgetExhausted: "The search hit its time budget — this is the best build found, not guaranteed to be the best that exists.",
  farmRespecDiagnostics: "{evaluations} builds checked across {sweeps} passes",
  farmRespecFailed: "The full search couldn't complete this time. Try Optimize again.",
  farmRespecTerminalTitle: "No respec recommendation right now",
  farmRespecTerminalDesc: "There isn't a build to recommend for this roster and pool.",
  farmRespecHeroesHeading: "Per-hero split",
  farmRespecLuckKeep: "Keep",
  farmRespecLuckHint: "Luck is left alone on purpose — the game doesn't refund it the same way every other stat is, and this planner never moves it.",
  farmRespecUnchangedGroupNote: "No respec needed for these — saves {gold} gold you don't have to spend.",
  farmRespecKeyCurrent: "Current",
  farmRespecKeyTarget: "Target",
  farmRespecKeyDelta: "Change",
  farmRespecFrontierHeading: "Cheaper respecs",
  farmRespecFrontierHeroCountOne: "1 hero",
  farmRespecFrontierHeroCountTwo: "2 heroes",
  farmRespecFrontierGainCost: "{gain}% gain for {cost} gold",
  farmRespecFrontierPaybackNone: "no gold payback",
  farmRespecRerankToggle: "Show ranking under this build",
  farmRespecRerankBanner: "Showing the table under the proposed respec build, not your current one.",
  farmRespecRerankCaption: "Farm Ranking table, showing phases under the proposed respec build, not the current one.",
} as const;
