/**
 * The Portuguese (Brazil) translation of `en.ts`. `FarmCopy` is a value-widening mapped type
 * (`export type FarmCopy = { readonly [K in keyof typeof farmEn]: string }` — `index.ts`), so this
 * file is annotated `: FarmCopy`, never `as FarmCopy`/`satisfies FarmCopy`/an index signature: the
 * annotation is what makes a missing key here a compile error naming the key (`TS2741`) and a
 * typo'd extra key a compile error too (`TS2353`) — both directions of the same guarantee.
 *
 * Key set and every `{placeholder}` must match `en.ts` exactly — `parity.test.ts` proves both at
 * runtime as a second, independent line of defence (a future widening of `FarmCopy` must not
 * silently disable the compile-time proof).
 */
import type { FarmCopy } from './index';

export const farmPtBR: FarmCopy = {
  phasesDifficultyLabel: "Dificuldade",
  phasesMapLabel: "Mapa",
  phasesPhaseId: "Fase #{id}",
  phasesMapName: "Nome do mapa",
  phasesMapFacts: "Mapa",
  phasesEconomy: "Economia",
  phasesSpawnMix: "Mix de props",
  phasesColShare: "Peso",
  phasesColGoldWiki: "Ouro (wiki)",
  phasesColGoldActual: "Ouro (seu)",
  phasesGateBadge: "Portão",
  phasesDifficulty: "Dificuldade",
  phasesStoneHp: "HP da pedra",
  phasesMitigation: "Mitigação",
  phasesPenNeedHint: "Precisa {pct}% de pen para ignorar toda mitigação",
  phasesPropCount: "Props no mapa",
  phasesAvgPropHp: "HP médio / prop",
  phasesTotalMapHp: "HP total est. do mapa",
  phasesBossHp: "HP chefe / jaula",
  phasesBossHint: "×10 pedra — pool 2×2 compartilhado",
  phasesBossGateHint: "Chefe do portão — limpar antes do timer",
  phasesGateTimer: "Timer do portão",
  phasesGateKey: "Chave consumida",
  phasesItemDrops: "Drops de item",
  phasesItemDropsValue: "Itens nível {range}",
  phasesXpPerProp: "XP por prop",
  phasesXpActualHint: "valor base × o multiplicador de XP da sua árvore de habilidades",
  phasesGoldComum: "Ouro (Comum)",
  phasesGoldActualHint: "valor base × (1 + o % de ouro do time da sua árvore de habilidades)",
  phasesAvgGold: "Ouro médio / prop",
  phasesMapGold: "Ouro do mapa est.",
  phasesJaulaSection: "Jaula",
  phasesJaulaSectionDesc: "A jaula corre pelo relógio de tempo jogado logado, não por sorteio de sala. Ela pode vir adiantada — a chance sobe de 0 até o teto ao longo da janela — e é garantida no fim.",
  phasesJaulaEarly: "Chance de adiantar nesta fase",
  phasesJaulaWindow: "Janela garantida",
  phasesJaulaWindowVip: "VIP {dur}",
  phasesJaulaHp: "HP da jaula",
  phasesJaulaChest: "Odds baú de herói",
  phasesDropsSection: "Chances de drop",
  phasesDropChest: "Baú de item",
  phasesDropKey: "Chave",
  phasesDropTime: "Baú de tempo",
  phasesDropGem: "Baú de gema",
  phasesDropStone: "Baú de pedra",
  phasesDropActualHint: "valor base + a Sorte da sua árvore de habilidades + a sorte média do seu esquadrão.",
  phasesDropsSectionDesc: "Quais drops podem cair depende de a fase ser um portão.",
  phasesDropGateOnly: "Apenas portões",
  phasesDropNonGateOnly: "Apenas não-portões",
  phasesHeroSection: "Seu herói",
  phasesHeroTip: "Usa Conta e a ficha equipada + pontos de cada herói.",
  phasesHeroPick: "Herói",
  phasesPenetration: "Penetração vs fase",
  phasesPenOk: "Penetração total",
  phasesPenShort: "Faltam {gap}%",
  phasesNormalHit: "Hit normal",
  phasesCritHit: "Hit crítico",
  phasesAvgHit: "Acerto médio (build)",
  phasesFieldTime: "Tempo em campo",
  phasesColNormalHit: "Normal",
  phasesColCritHit: "Crít.",
  phasesColFieldTime: "Campo",
  phasesNoHeroes: "Importe heróis no Planner para ver penetração e hits-to-kill aqui.",
  phasesNoHeroesLink: "importe um save para liberar linhas por herói.",
  phasesSquadSection: "Top {slots} por DPS solo",
  phasesSquadTip: "Soma dos maiores DPS solo sustentados do roster (mesma Conta), até o limite de slots da casa.",
  phasesSquadCombinedDps: "DPS sustentado combinado",
  phasesClearEstimate: "Tempo est. de clear",
  phasesClearDisclaimer: "Modelo do ranking — sua rotação inteira sob os limites de casa e campo, cobrando golpes inteiros por prop. Não é HP do mapa ÷ DPS combinado.",
  panelContext: "Contexto",
  phaseHint: "Insira o número da fase no {wiki}.",
  phaseHelp: "wiki",
  phaseHelpAria: "Wiki do Bomb Farm — fases",
  mitAutoHint: "da fase",
  phase: "Fase",
  mitPct: "Mit %",
  cycle: "Ciclo",
  cycleSerial: "Em série",
  cycleWiki: "Wiki",
  walkS: "Caminhada (s)",
  extraDmg: "Dano extra %",
  prop: "Prop alvo",
  contextTip: "Pavio {f}s · descanso {r}m · HP da pedra {hp}",
  colProp: "Alvo",
  colHp: "HP",
  colHits: "Hits",
  colNeed: "Falta%",
  bossRow: "boss/jaula",
  avgRow: "média",

  farmRankingColPhase: "Fase",
  farmRankingColMitigation: "Mitigação",
  farmRankingColGold: "Ouro",
  farmRankingColChests: "Baú de item",
  farmRankingColKeys: "Chave",
  farmRankingColGems: "Baú de gema",
  farmRankingColTimePieces: "Baú de tempo",
  farmRankingColXp: "XP",
  farmRankingColItemLevel: "Nível de item",
  farmRankingColClearTime: "Tempo de clear",
  farmRankingColOneShot: "Um golpe",

  farmRankingTitle: "Ranking de Farm",
  farmRankingCaption: "Todas as fases da wiki rankeadas pelo que pagam a esta conta por hora",
  farmRankingEmptyNoRosterTitle: "Ainda sem roster",
  farmRankingEmptyNoRosterDesc: "Adicione heróis no Planner para rankear fases para sua conta.",
  farmRankingEmptyNoHeroesTitle: "Nenhum herói habilitado",
  farmRankingEmptyNoHeroesDesc: "Habilite ao menos um herói no pool de rotação abaixo para ver as taxas.",
  farmRankingEmptyComputeFailedTitle: "Não foi possível calcular o ranking",
  farmRankingEmptyComputeFailedDesc: "Algo deu errado ao estimar as taxas desta conta.",
  farmRankingEmptyNoMatchesTitle: "Nenhuma fase corresponde a estes filtros",
  farmRankingEmptyNoMatchesDesc: "Limpe um filtro acima para ver mais fases.",
  farmRankingFilterUnlockedLabel: "Apenas desbloqueadas",
  farmRankingFilterUnlockedDisabledReason: "Este filtro precisa de um save com fase máxima conhecida.",
  farmRankingFilterAtoLabel: "Filtro de dificuldade",
  farmRankingFilterAtoAll: "Todas as dificuldades",
  farmRankingFilterGateLabel: "Portão",
  farmRankingFilterGateAll: "Todas as fases",
  farmRankingFilterGateOnly: "Apenas portões",
  farmRankingFilterGateNonGate: "Apenas não-portões",
  farmRankingFilterItemLevelLabel: "Nível mínimo do item",
  farmRankingFilterItemLevelAll: "Qualquer nível",
  farmRankingFilterItemLevelOption: "Nível {level}+",
  farmRankingPoolLabel: "Pool de rotação",
  farmRankingPoolHeroAria: "Incluir {name} na estimativa de farm",
  farmRankingContentionTitle: "Seu campo é o gargalo",
  farmRankingContentionTitleMaxSlots: "Seu campo está saturado",
  farmRankingContentionDesc:
    "Em {pct} do tempo um herói descansado espera no banco porque suas {slots} vagas de campo estão todas ocupadas. Mais vagas de campo é a solução direta — o limite é {max}. A estimativa de ouro/h já cobra essa espera: ela custa cerca de {cost} da taxa que você teria com vaga para todos. Desligar heróis acima também reduz a espera, mas costuma reduzir o total junto: um herói que só às vezes pega vaga ainda produz enquanto está nela.",
  farmRankingContentionDescMaxSlots:
    "Em {pct} do tempo um herói descansado espera no banco porque suas {slots} vagas de campo estão todas ocupadas. {slots} é o máximo, então essa espera é estrutural — não há mais vagas para comprar. A estimativa de ouro/h já cobra essa espera: ela custa cerca de {cost} da taxa que você teria com vaga para todos. Desligar heróis acima também reduz a espera, mas costuma reduzir o total junto: um herói que só às vezes pega vaga ainda produz enquanto está nela.",
  farmRankingReturnBonusLabel: "Bônus de Retorno",
  farmRankingReturnBonusOff: "Desligado",
  farmRankingReturnBonusOn: "Ligado",
  farmRankingReturnBonusVip: "VIP",
  farmRankingGateBadge: "Portão",
  farmRankingOneShotYes: "Sim",
  farmRankingOneShotNo: "Não",
  farmRankingOneShotTooltipYes: "Todo herói habilitado mata todo tipo de prop com um golpe nesta fase.",
  farmRankingOneShotTooltipNo: "Nem todo herói habilitado mata todo prop com um golpe — esperado {htk} golpes por prop.",
  farmRankingSortedBy: "Ordenado por {column}, {direction}",
  farmRankingSortAsc: "crescente",
  farmRankingSortDesc: "decrescente",
  farmRankingCurrentPhase: "Fase atual",

  farmRespecOptimize: "Otimizar",
  farmRespecOptimizeBusy: "Calculando…",
  farmRespecHeadlineGain: "Pelo menos {pct}% a mais por hora",
  farmRespecGateFailed: "A checagem rápida não pôde rodar desta vez. Otimizar continua disponível para a resposta completa.",
  farmRespecPaybackHours: "Se paga em {hours} h",
  farmRespecPaybackNoChange: "O ouro por hora não muda, então não há retorno de ouro a reportar.",
  farmRespecPanelHeading: "Consultor de respec",
  farmRespecClose: "Fechar",
  farmRespecPanelGain: "{pct}% a mais por hora",
  farmRespecMetricGold: "Ouro / h",
  farmRespecMetricChests: "Baús / h",
  farmRespecMetricPhase: "Fase",
  farmRespecMetricPhaseSame: "(mesma fase)",
  farmRespecMetricCost: "Custo do respec",
  farmRespecMetricPayback: "Retorno",
  farmRespecPaybackTip: "O retorno divide o custo do respec pelo ouro extra por hora que o novo build ganha — a diferença entre os dois números de Ouro/h acima, não a nova taxa sozinha. Se o build proposto ganha menos ouro que o atual, ou a mesma quantidade, não há retorno em ouro a reportar.",
  farmRespecBestFound: "Este é o melhor build que a busca encontrou — não é prova de que não exista um melhor.",
  farmRespecBudgetExhausted: "Esta busca parou no limite de quantos builds ela pode testar, e não porque tinha ficado sem melhorias para fazer.",
  farmRespecDiagnostics: "{evaluations} builds testados em {sweeps} passadas",
  farmRespecFailed: "A busca completa não conseguiu terminar desta vez. Tente Otimizar de novo.",
  farmRespecTerminalTitle: "Nenhuma recomendação de respec agora",
  farmRespecTerminalDesc: "Não há um build para recomendar para este roster e pool.",
  farmRespecHeroesHeading: "Divisão por herói",
  farmRespecLuckKeep: "Manter",
  farmRespecLuckHint: "Sorte é deixada de lado de propósito — o jogo não a reembolsa como reembolsa os outros atributos, e este planner nunca a move.",
  farmRespecUnchangedGroupNote: "Nenhum respec necessário para estes — economiza {gold} de ouro que você não precisa gastar.",
  farmRespecKeyCurrent: "Atual",
  farmRespecKeyTarget: "Alvo",
  farmRespecKeyDelta: "Mudança",
  farmRespecFrontierHeading: "Respecs mais baratos",
  farmRespecFrontierHeroCountOne: "1 herói",
  farmRespecFrontierHeroCountTwo: "2 heróis",
  farmRespecFrontierGainCost: "{gain}% de ganho por {cost} de ouro",
  farmRespecFrontierPaybackNone: "sem retorno em ouro",
  farmRespecRerankToggle: "Mostrar ranking sob este build",
  farmRespecRerankBanner: "Mostrando a tabela sob o build de respec proposto, não o seu atual.",
  farmRespecRerankCaption: "Tabela de Ranking de Farm, mostrando fases sob o build de respec proposto, não o atual.",
};
