import { execSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const committedDir = join(packageRoot, 'src/icon/game');

const headerTemplate = [
  '// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.',
  '// Source: packages/ui/icons/game/<basename>.svg',
];

function stampHeaders(outDir) {
  for (const file of readdirSync(outDir).filter((name) => name.endsWith('.tsx'))) {
    const path = join(outDir, file);
    const source = readFileSync(path, 'utf8');
    const basename = file.replace(/\.tsx$/, '');
    const header = headerTemplate.map((line) => line.replace('<basename>', basename)).join('\n');

    if (source.startsWith(header)) {
      continue;
    }

    const withoutHeader = source.replace(/^\/\/ GENERATED by.*\n\/\/ Source:.*\n+/, '');
    writeFileSync(path, `${header}\n${withoutHeader}`);
  }
}

let tempDir;
try {
  tempDir = mkdtempSync(join(tmpdir(), 'icons-check-'));

  execSync(`svgr --config-file svgr.config.cjs --out-dir "${tempDir}" icons/game`, {
    cwd: packageRoot,
    stdio: 'pipe',
  });
  stampHeaders(tempDir);

  const committedFiles = readdirSync(committedDir)
    .filter((name) => name.endsWith('.tsx'))
    .sort();
  const generatedFiles = readdirSync(tempDir)
    .filter((name) => name.endsWith('.tsx'))
    .sort();

  const differences = [];
  const allFiles = new Set([...committedFiles, ...generatedFiles]);

  for (const file of [...allFiles].sort()) {
    const committedPath = join(committedDir, file);
    const generatedPath = join(tempDir, file);
    const inCommitted = committedFiles.includes(file);
    const inGenerated = generatedFiles.includes(file);

    if (!inCommitted) {
      differences.push(`${file} (extra in regenerated output)`);
      continue;
    }
    if (!inGenerated) {
      differences.push(`${file} (missing from regenerated output)`);
      continue;
    }

    const committed = readFileSync(committedPath, 'utf8');
    const generated = readFileSync(generatedPath, 'utf8');
    if (committed !== generated) {
      differences.push(file);
    }
  }

  if (differences.length > 0) {
    console.error('icons:check failed — committed components differ from a fresh SVGR run:');
    for (const name of differences) {
      console.error(`  ${name}`);
    }
    process.exit(1);
  }
} finally {
  if (tempDir) {
    rmSync(tempDir, { recursive: true, force: true });
  }
}
