/**
 * The two per-directory guards (`fixture-corpus.test.ts` for `sheet-math/`,
 * `farm-rate-fixture-corpus.test.ts` for `farm-rate/`) each prove their own directory's captures
 * are fully inventoried in its README. Neither says anything about a THIRD file: nothing stopped
 * one from landing anywhere else in `fixtures/**` with no README governing it at all.
 *
 * This is the bound: every committed `.json` under `fixtures/` must be either directly inside a
 * GOVERNED directory (one with a README + completeness guard, like the two above) or on the
 * EXCEPTIONS list below, named with its reason. A file in neither category fails here by
 * construction — the fix is to add its directory to {@link GOVERNED_CAPTURE_DIRS} and give it the
 * same README + completeness guard the two existing directories have, or to add a reasoned
 * {@link EXCEPTIONS} entry, never to widen this file's reach to stop noticing it.
 *
 * The previous version of this guard only checked files named `save-`/`payload-YYYYMMDD-...`,
 * which made any other naming convention invisible to it by construction —
 * `fidelity-gate/export-capture.json` is the existing, deliberately-undocumented-here example
 * (see its EXCEPTIONS entry). A same-shaped file under a fourth naming convention would have
 * reproduced that blind spot with no failure and no edit required; this version has no such gap,
 * because every committed fixture `.json` is accounted for by name, not by pattern.
 */
import { readdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(here, 'fixtures');

/**
 * Directories under `fixtures/` that carry a README provenance manifest AND a guard proving it
 * complete (README row per file, digest matching, no dangling row) — measured today as exactly
 * `fixture-corpus.test.ts` and `farm-rate-fixture-corpus.test.ts`.
 */
const GOVERNED_CAPTURE_DIRS = ['sheet-math', 'farm-rate'];

/**
 * Every committed fixture `.json` NOT inside a governed directory, keyed by its path relative to
 * `fixtures/`, with why it needs no README manifest of that shape. Per-file, not per-directory: a
 * new file dropped into `api/` or `fidelity-gate/` alongside an already-exempted one still fails
 * here until it earns its own reasoned entry.
 */
const EXCEPTIONS: Record<string, string> = {
  'api/assembled-payload-after.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'api/assembled-payload-before.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'api/assembled-payload-drift.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'api/assembled-payload-partial.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'api/rotation-snapshot.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'api/rotation-snapshot-ready.json':
    'generated by generate-domain-fixtures.mjs; tools/derived-fixture-drift.test.mjs checks it against the generator output directly, not a README manifest',
  'farm-basis-parity-expected.json':
    "a frozen expected-output literal (computeHeroFarmFacts + computeFarmRates), not a raw account capture — see farm-basis-parity.test.ts's own header comment for provenance",
  'fidelity-gate/export-capture.json':
    'provenance is pair.json plus the pinned cross-directory duplicate check in tools/fixture-corpus-parity.test.mjs (AD-070), not a README manifest',
  'fidelity-gate/live-capture.json':
    "export-capture.json's paired live-memory read; same provenance as that entry",
  'fidelity-gate/pair.json':
    'the machine-readable provenance manifest itself (capturedAt/gameBuild) for the two files above',
  'i18n-strings-main.json':
    "pre-existing i18n fixture with zero domain-side consumer of this copy — apps/web owns the live one this mirrors (see fixture-corpus.test.ts's orphan-sweep comment)",
  'invariance/baseline.json': 'a recorded invariance baseline written by helpers/invariance-record.ts, not a raw account capture',
  'live-capture-energy-fractions.json':
    'a live memory-scan capture consumed by live/field-countdown.test.ts, named for its content rather than the save-/payload- convention',
  'rejection/pre-update-save.json':
    'a purpose-built rejection fixture (MSG-12/13) that must contain the retired fields verbatim to prove parseSaveFile rejects a save shaped like this',
  'rejection/truncated-save.json': 'sibling rejection fixture (MSG-13) — an empty skills.totals, no retired fields to carry',
  'storage-roundtrip-20260729.json':
    "pre-existing storage-roundtrip snapshot with zero domain-side consumer of this copy — apps/web owns the live one this mirrors (see fixture-corpus.test.ts's orphan-sweep comment)",
};

function listJsonFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      listJsonFiles(full, acc);
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      acc.push(full);
    }
  }
  return acc;
}

describe('fixture corpus bounds: every committed fixture json is governed or a named exception', () => {
  const allJsonFiles = listJsonFiles(FIXTURES_DIR).map((f) => relative(FIXTURES_DIR, f).replace(/\\/g, '/'));

  it('non-vacuity: the walk finds committed fixture JSON', () => {
    expect(allJsonFiles.length, `walked ${FIXTURES_DIR}`).toBeGreaterThan(0);
  });

  it('every committed fixture json lives directly inside a governed directory or is a named exception', () => {
    const offenders: string[] = [];
    for (const file of allJsonFiles) {
      const parts = file.split('/');
      const dir = parts.length >= 2 ? parts[parts.length - 2] : null;
      if (dir !== null && GOVERNED_CAPTURE_DIRS.includes(dir)) continue;
      if (file in EXCEPTIONS) continue;
      offenders.push(file);
    }
    expect(
      offenders,
      `fixture json outside a governed directory (${GOVERNED_CAPTURE_DIRS.join(', ')}) and not a named exception: ` +
        `${offenders.join(', ')} — add its directory to GOVERNED_CAPTURE_DIRS with a README + completeness guard, ` +
        'or add a reasoned EXCEPTIONS entry',
    ).toEqual([]);
  });

  it('every EXCEPTIONS entry still names a file that exists and carries a non-empty reason', () => {
    const actual = new Set(allJsonFiles);
    const stale = Object.keys(EXCEPTIONS).filter((f) => !actual.has(f));
    expect(stale, 'EXCEPTIONS entry naming a file that no longer exists').toEqual([]);
    expect(Object.values(EXCEPTIONS).every((reason) => reason.trim().length > 0)).toBe(true);
  });
});
