/**
 * Every player-facing string the per-hero detail panels print, flat and typed.
 *
 * These live HERE rather than in a host-supplied contract (`roster-copy.ts`, `hero-panel-copy.ts`)
 * because none of them is vocabulary a host already prints elsewhere: a roll band, a percentile,
 * "not modelled", the fuse floor, an uncertain placement and the two empty-state reasons appear on
 * no other screen. Making both hosts supply them in two languages would give every string two
 * owners and guarantee drift.
 *
 * `as const` is load-bearing twice over: it makes `HeroCopy` (`index.ts`) a mapped type over this
 * exact key set, and it keeps the values as string LITERALS, so a host that spreads this object
 * into a wider dictionary of its own keeps the literal types it had before.
 */
export const heroEn = {
  heroDetailIdentityTitle: "Identity",
  heroDetailIdentityRarity: "Rarity",
  heroDetailIdentityGrade: "Grade",
  heroDetailIdentityLevel: "Level",
  heroDetailIdentityPower: "Power",
  heroDetailIdentityMarketable: "Marketable",
  heroDetailIdentityNotMarketable: "Not marketable",
  heroDetailIdentityMarketValue: "Market value",

  heroDetailRunesTitle: "Runes",
  heroDetailRunesTip:
    "Timed buffs the game is applying to this hero right now. Every figure on this screen counts them, and each one goes when its play time runs out.",
  heroDetailRuneStrength: "+{pct}%",
  heroDetailRunePlayLeft: "{hours}h of buff left",
  heroDetailRuneAxisXp: "XP",
  heroDetailRuneAxisGold: "Gold",

  heroDetailPowerTitle: "Power",
  heroDetailPowerTip:
    "The game's own Power figure, taken apart. Power is ten times attack multiplied by one factor per statistic; each factor's share is how much of that stack it lifts, measured from a hero with none of the statistic.",
  heroDetailPowerPick: "Pick a factor to see Power across its range.",
  heroDetailPowerRunesActive: "Includes active runes · {value} without them",
  heroDetailPowerWithheld:
    "This is the game's stored figure, without runes. The breakdown is built on the hero's spent points, which could not be read.",
  heroDetailPowerFactorCrit: "Crit (chance × damage)",
  heroDetailPowerFactorSpeed: "Speed",
  heroDetailPowerFactorRange: "Range (Wide Blast)",
  heroDetailPowerFactorUtility: "Utility (luck + energy)",
  heroDetailPowerFactorEnergy: "Energy",
  heroDetailPowerFactorPenetration: "Penetration",
  heroDetailPowerFactorCooldown: "Cooldown",
  heroDetailPowerFactorAttack: "Attack",
  heroDetailPowerAnchor: "anchor",
  heroDetailPowerShareBar: "Share of Power by factor",
  heroDetailPowerSegment: "{factor}: {share}",
  heroDetailPowerAxisAmpla: "Wide Blast level",
  heroDetailPowerChart: "Power against {stat}",
  heroDetailPowerNow: "now",
  heroDetailPowerCap: "cap",
  heroDetailPowerReadout: "{stat} {value} → Power {power} ({delta}, {pct} from now)",
  heroDetailPowerReadoutCapped: "At 100% crit chance: {power}",
  heroDetailPowerCappedLegend: "Dashed: with crit chance at 100%",
  heroDetailPowerExtrapolated: "Past the highest cooldown checked ({pct}), this is extrapolated.",

  heroDetailRollTitle: "Birth roll",
  heroDetailRollQuality: "Roll quality",
  heroDetailRollQualityNote:
    "The average of this hero's eight roll percentiles: for each statistic, how far into its own band the roll landed. 50 is an average roll everywhere, 90 is near the top of every band.",
  heroDetailRollColStat: "Stat",
  heroDetailRollColBand: "Band",
  heroDetailRollColPosition: "Position",
  heroDetailRollValue: "Rolled",
  heroDetailRollBand: "Rolled inside {range}",
  heroDetailRollPercentile: "{pct}% into its band",
  heroDetailRollGradePlacement: "Where it sits in grade {letter}",
  heroDetailRollPermanent:
    "The birth roll is permanent: it never changes with level, stars, gear or spent points.",
  heroDetailRollNoBirthRoll: "This hero has no birth roll, so there is nothing to place.",
  heroDetailRollNoBounds:
    "This hero has no roll bounds, so its position inside them cannot be measured.",
  heroDetailRollComputedDisagrees:
    "The quality we compute lands on a different letter than the one the game stored.",
  heroDetailRollStoredLetterStands: "The stored letter is the game's answer and stands.",
  heroDetailRollStoredLetter: "Stored grade",
  heroDetailRollComputedLetter: "Our estimate",
  heroDetailRollPlacementUncertain: "Read the placement below as uncertain.",

  heroDetailAbilitiesTitle: "Abilities",
  heroDetailAbilitiesLevelOfMax: "{level} of {max}",
  heroDetailAbilitiesEffect: "Modelled effect",
  heroDetailAbilitiesOnSheetTag: "On sheet",
  heroDetailAbilitiesNotModelled:
    "The model carries no effect for this ability, so it cannot be priced.",
  heroDetailAbilitiesMaxed: "Already at its maximum level, with no next level to buy.",
  heroDetailAbilitiesNextLevelGain: "One more level is worth {pct}% to this hero",
  heroDetailAbilitiesAuraAtCeiling:
    "Your roster is already at this aura's field-wide ceiling, so the next level buys nothing.",
  heroDetailAbilitiesNotMeasured:
    "The model carries this effect, but it lands outside what sustained damage per second measures.",
  heroDetailAbilitiesNoBirthRoll:
    "Without a birth roll this hero cannot be valued, so no ability of its can be priced.",
  heroDetailAbilitiesPoints: "Ability points",
  heroDetailAbilitiesPointsValue: "{spent} of {budget} spent",
  heroDetailAbilitiesNone: "This hero owns no abilities.",

  heroDetailCombatTitle: "Combat",
  heroDetailCombatNormalHit: "Normal hit",
  heroDetailCombatCritHit: "Critical hit",
  heroDetailCombatAvgHit: "Average hit",
  heroDetailCombatFieldTime: "Time on field",
  heroDetailCombatFuseTime: "Fuse time",
  heroDetailCombatUptime: "Uptime",
  heroDetailCombatDps: "DPS",
  heroDetailCombatActiveDps: "Active DPS",
  heroDetailCombatSustainedDps: "Sustained DPS",
  heroDetailCombatPenetration: "Penetration vs mitigation",
  heroDetailCombatDamageThrough: "Damage that lands",
  heroDetailCombatHitsToKill: "Hits to kill",
  heroDetailCombatProps: "Props",
  heroDetailCombatPhase: "Phase {name}",
  heroDetailCombatPhaseFromFarm: "This is the phase your Farm screen is set to.",
  heroDetailCombatPhaseOverridden: "You are looking at a different phase than your Farm screen.",
  heroDetailCombatFuseFloor: "Fuse floor",
  heroDetailCombatFuseFloorHint: "The fuse time cannot go below {secs}s.",
  heroDetailCombatCdrCeiling: "Cooldown reduction ceiling",
  heroDetailCombatCdrCeilingReached: "Further cooldown reduction buys nothing.",
  heroDetailCombatNoProps: "There are no props on this phase.",

  heroDetailPhaseTitle: "Phase these numbers are for",
  heroDetailPhaseLabel: "Phase",
  heroDetailPhaseAria: "Which phase these numbers are computed at",
  heroDetailPhaseUseCurrent: "Back to your current phase",
  heroDetailPhaseSearchPlaceholder: "Hard, Normal 2-1, or 151",
  heroDetailPhaseNoMatch: "No phase matches that.",
  heroDetailPhaseMoreMatches: "Showing {shown} of {matched} — keep typing to narrow.",

  heroDetailAurasTitle: "Abilities & auras",
  heroDetailAurasTip:
    "What the figures on this stage are priced with. A team aura is a property of the field, so everyone standing in it gets the same total, capped per aura. This hero's own aura counts at its rank and cannot be switched off; any other aura is off until you switch it on, and then counts at its cap, whoever carries it. The Farm screen and the Optimizer price the same auras by each carrier's predicted uptime instead, so their figures can differ from these. Baton Pass is counted here as if its pulse never lapsed — the whole stint at its level, +80% at the cap — while the Farm screen and the Optimizer count only the 120 s each entry lights.",
  heroDetailAurasTeamGroup: "Team auras",
  heroDetailAurasOwnGroup: "Own abilities",
  heroDetailAuraOwnTag: "own",
  heroDetailAuraNotHereTag: "not here",
  heroDetailAuraNotModelledTag: "not modelled",
  heroDetailAuraSwitchAria: "Count {name} at its cap",
  heroDetailAuraDeltaIfOn: "+{value}% if on",
  heroDetailAuraDeltaIfOff: "−{value}% if off",
  heroDetailAurasNoOwnAbilities: "This hero has no ability of its own in force.",

  heroDetailBreakdownHint: 'Hover or focus a card for the formula behind it and what it reads; the cards it is wired to stay lit.',
  heroDetailBreakdownRowSheet: "Sheet",
  heroDetailBreakdownRowFactors: "Factors",
  heroDetailBreakdownRowPerHit: "Per hit · cadence",
  heroDetailBreakdownRowDps: "DPS",
  heroDetailBreakdownFormulaMitF: "1 − mit × (1 − pen)",
  heroDetailBreakdownFormulaDmg: "pack × extra × pulse",
  heroDetailBreakdownFormulaCritFactor: "1 + cc × cd",
  heroDetailBreakdownFormulaFuse: "max(2 × (1 − cdr), floor)",
  heroDetailBreakdownFormulaField: "energy ÷ drain",
  heroDetailBreakdownFormulaRest: "House rest ÷ 60",
  heroDetailBreakdownFormulaHit: "atk × mitF × dmg",
  heroDetailBreakdownFormulaCriticalHit: "hit × (1 + cd)",
  heroDetailBreakdownFormulaAvgHit: "hit × crit factor",
  heroDetailBreakdownFormulaBombs: "1 ÷ E[max(fuse, hop ÷ speed)]",
  heroDetailBreakdownFormulaUptime: "field ÷ (field + rest)",
  heroDetailBreakdownFormulaActive: "avg × abilities × bombs/s × spread × 0.9",
  heroDetailBreakdownFormulaSustained: "active × uptime",
  heroDetailBreakdownTermPhaseMit: "phase mitigation",
  heroDetailBreakdownTermPenetration: "penetration",
  heroDetailBreakdownTermAbilities: "abilities",
  heroDetailBreakdownTermPack: "pack",
  heroDetailBreakdownTermExtra: "extra",
  heroDetailBreakdownTermPulse: "pulse, held up",
  heroDetailBreakdownTermAttack: "attack",
  heroDetailBreakdownTermMitF: "mitigation factor",
  heroDetailBreakdownTermDmg: "damage multiplier",
  heroDetailBreakdownTermHit: "hit",
  heroDetailBreakdownTermCritChance: "crit chance",
  heroDetailBreakdownTermCritDmg: "crit damage",
  heroDetailBreakdownTermCritFactor: "critical factor",
  heroDetailBreakdownTermCdr: "cooldown reduction",
  heroDetailBreakdownTermFuseFloor: "floor",
  heroDetailBreakdownTermFuse: "fuse",
  heroDetailBreakdownTermWalk: "walk speed",
  heroDetailBreakdownTermBand: "band",
  heroDetailBreakdownTermCycle: "cycle",
  heroDetailBreakdownTermEnergy: "energy",
  heroDetailBreakdownTermDrain: "drain",
  heroDetailBreakdownTermRestSeconds: "rest",
  heroDetailBreakdownTermField: "field time",
  heroDetailBreakdownTermAvgHit: "average hit",
  heroDetailBreakdownTermBombs: "bombs/s",
  heroDetailBreakdownTermRangeMult: "blast spread",
  heroDetailBreakdownTermAiEfficiency: "AI efficiency",
  heroDetailBreakdownTermActiveDps: "active DPS",
  heroDetailBreakdownReads: "Reads",
  heroDetailBreakdownNoteFuseAtCeiling:
    "At the ceiling: the fuse cannot go below {floor}s, so cooldown reduction past {cap}% buys nothing.",
  heroDetailBreakdownNoteFuseFloor:
    "The fuse cannot go below {floor}s; cooldown reduction stops paying at {cap}%.",
  heroDetailBreakdownNoteAvgHitEqualsHit: "Equal to Hit: crit chance is zero, so no hit crits.",
  heroDetailBreakdownNoteHitWithoutExpectedBlasts:
    "What one blast shows in the game. {names} adds damage no single blast shows, so it is left out here; Active DPS carries it as ×{mult}.",
  heroDetailBreakdownNoteFieldWithoutTeamDrain: "Without the team's {name} this would be {secs}s.",
  heroDetailBreakdownNoteActiveConstants:
    "Blast spread is 1 + 0.5 per cell of range ({cells} cells here): each cell past the epicentre reaches half a hit's worth of props on average. Range is always whole cells — Wide Blast raises it at levels 10 and 20. AI efficiency is the game's flat ×0.9 for a fielded hero's re-targeting and misplaced bombs; every Active DPS in this app carries it.",
  heroDetailBreakdownNoteBatonHeld:
    "Baton Pass is counted as if its pulse never lapsed: the whole stint at +{pct}%. The Farm page and the Optimizer count only the 120 s each entry lights.",
  heroDetailBreakdownPenCovers: "nothing lost to mitigation",
  heroDetailBreakdownPenShort: "{lost}% of each hit lost to mitigation",
  heroDetailBreakdownNotePenPierced: "Penetration is at 100%, so the phase’s mitigation takes nothing off a hit.",
  heroDetailBreakdownNotePenPartial:
    "Penetration pierces a share of the phase’s mitigation, not points off it: {pen}% of the phase’s {mit}% is pierced, so {lost}% of each hit is still lost. Only 100% penetration loses nothing.",
  heroDetailBreakdownIconOff: "{name} — switched off",
  heroDetailBreakdownMatrixTitle: "Sheet stats",
  heroDetailBreakdownColStat: "Stat",
  heroDetailBreakdownColHero: "Hero",
  heroDetailBreakdownColGear: "Gear",
  heroDetailBreakdownColAbility: "Ability",
  heroDetailBreakdownColTree: "Skill tree",
  heroDetailBreakdownColRune: "Rune ×",
  heroDetailBreakdownColSheetTotal: "Sheet total",
  heroDetailBreakdownColAura: "Aura ×",
  heroDetailBreakdownColEffective: "Effective",
  heroDetailBreakdownAuraOff: "off",
  heroDetailBreakdownHeroCellAria: "How {stat}'s hero figure is built",

  heroDetailSheetTitle: "Statistic sheet",
  heroDetailPointsTitle: "Points spent",
  heroDetailBreakdownTitle: "Per-statistic breakdown",
  heroDetailGearTitle: "Equipped loadout",
  heroDetailGearSlotContribution: "Per-slot contribution",
  heroDetailGearTotals: "Gear totals",
  heroDetailGearCompareTitle: "Loadout comparison",
  heroDetailNextStatTitle: "Recommended next statistic",
  heroDetailNextStatModeDamage: "Damage",
  heroDetailNextStatModeFarming: "Farming",
  heroDetailNextStatFarmUnavailable: "A farming recommendation is not available here: {reason}",

  heroDetailEmptyNoAccount: "The game is not running, or the account has not been read yet.",
  heroDetailEmptyNoHeroes: "This account has no heroes.",
} as const;
