/**
 * The Portuguese (Brazil) translation of `panel-en.ts`.
 *
 * Annotated `: StatPanelCopy` / `: GearPanelCopy`, never `as`/`satisfies`/an index signature —
 * the annotation is what makes a missing member a compile error naming it (`TS2741`) and a typo'd
 * extra member a compile error too (`TS2353`). `index.ts` records why each of the three
 * alternatives destroys that guarantee.
 *
 * Member set and every `{placeholder}` must match `panel-en.ts` exactly — `panel-parity.test.ts`
 * proves both at runtime as a second, independent line of defence.
 */
import type { GearPanelCopy, StatPanelCopy } from './index';

export const statPanelPtBR: StatPanelCopy = {
  statFull: {
    attack: 'Ataque',
    energy: 'Energia',
    speed: 'Velocidade',
    critChance: 'Chance de Crítico',
    critDmg: 'Dano Crítico',
    penetration: 'Penetração',
    cdr: 'Redução de recarga',
    luck: 'Sorte',
  },
  statShort: {
    attack: 'Ataque',
    energy: 'Energia',
    speed: 'Velocidade',
    critChance: 'Crít %',
    critDmg: 'Dano crít. +%',
    penetration: 'Pen %',
    cdr: 'Redução de recarga (%)',
    luck: 'Sorte',
  },
  fieldRequired: 'obrigatório',
  colStat: 'Stat',
  panelSheet: 'Atributos',
  sheetTip: 'Breakdown da ficha do herói no jogo a partir do save: roll ao nascer até nível, estrelas, habilidades de ficha (Olho Clínico, Ponta de Diamante, Golpe Brutal), gear, pontos gastos e árvore de habilidades. O Total é a soma sem teto do modelo; quando chance de crítico ou redução de recarga passam do teto de exibição do jogo, Acima do teto mostra quanto está sendo desperdiçado.',
  sheetTipNeedBirth: 'Este herói ainda não tem roll ao nascer guardado — reimporte seu save para o planner remontar a ficha pela origem. Heróis locais antigos precisam de um import novo.',
  colSheetBirth: 'Ao nascer',
  colSheetDeltaLevel: 'Δ nível',
  colSheetDeltaStars: 'Δ estrela',
  colSheetDeltaAbility: 'Δ habilidade',
  colSheetDeltaGear: 'Δ gear',
  colSheetDeltaPoints: 'Δ pontos',
  colSheetDeltaTree: 'Δ árvore',
  colSheetTotal: 'Total',
  colSheetOverCap: 'Acima do teto',
  panelPoints: 'Pontos',
  abilitiesSpent: '{spent} / {max} pontos',
  pointsUnspentBanked: '+{count} não gastos',
  pointsOverBudgetWarning: 'Estes pontos de atributo não fecham: {spent} pontos em um herói de nível {level}, e o jogo concede apenas um por nível. Importe um save novo — se continuar assim, avise no Discord.',
  pointsStepMinusFiveAria: 'Remover 5 pontos de {stat}',
  pointsStepPlusFiveAria: 'Adicionar 5 pontos a {stat}',
  reset: 'Zerar',
  resetAdviceGainLine: 'Uma checagem rápida encontrou um possível ganho de DPS efetivo de pelo menos ~{pct}%. Otimizar build no modo DPS dá a resposta definitiva.',
  colPerPt: '/pt',
  colAfter: 'Depois',
  colPreview: 'Prévia',
  metricNextPoint: 'Próximo ponto',
  rankFarmNoPool: 'Ordenado por dano — não há rotação de farm para comparar.',
  rankFarmNoRate: 'Ordenado por dano — nenhuma fase farmável para essa rotação ainda.',
  rankFarmAddedToPool: 'Este herói não está na sua rotação de farm — ordenado como se você o adicionasse.',
  modeDps: 'DPS',
  modeFarm: 'Farm',
  optimizeModeLabel: 'Alvo do Otimizar build',
  optimizeBuildButton: 'Otimizar build',
  optimizeBuildNoBudgetReason: 'Nenhum ponto para alocar neste nível ainda.',
  optimizeBuildBudgetExhausted: 'A busca tinha um limite e parou antes do fim — este é o melhor resultado dentro desse limite.',
  optimizeBuildHeroDisabledNote: 'Este herói está desativado, então não entra nas recomendações automáticas de reset.',
  optimizeBuildKeptCurrent: 'Essa busca não superou sua alocação atual.',
  optimizeBuildResultLine: 'Melhor alocação encontrada por essa busca: cerca de {pct}% a mais de DPS efetivo.',
  optimizeBuildFarmKeptCurrent: 'Essa busca não superou sua alocação atual para farm.',
  optimizeBuildFarmResultLine: 'Melhor alocação encontrada por essa busca: cerca de {pct}% a mais de ouro por hora para sua rotação.',
  optimizeBuildFarmNoPool: 'Nenhuma rotação de farm para comparar. Adicione este herói à sua rotação, ou troque o alvo para DPS.',
  optimizeBuildFarmNoRate: 'Nenhuma fase farmável para essa rotação ainda — nada para comparar.',
  previewApplyButton: 'Aplicar prévia',
  previewClearButton: 'Limpar prévia',
  previewRespecNote: 'Aplicado no planner — use um reset de verdade no jogo para bater com essa build.',
  effectiveMitF: 'Fator de mitigação',
  effectiveDmg: 'Multiplicador de dano',
  effectiveHit: 'Hit',
  effectiveCriticalHit: 'Critical Hit',
  effectiveCritFactor: 'Fator de crítico',
  effectiveFuse: 'Pavio',
  effectiveBombsPerSec: 'Bombas / s',
  effectiveField: 'Tempo em campo',
  effectiveRest: 'Descanso',
  effectiveUptime: 'Aproveitamento',
  effectiveActiveDps: 'DPS ativo',
  effectiveSustainedDps: 'DPS sustentado',
  bdLedgerTotal: 'Efetivo',
  bdSrcBase: 'Roll base',
  bdSrcLevel: 'Nível',
  bdSrcStars: 'Estrelas',
  bdSrcSheetAbilities: 'Habilidades de ficha',
  bdSrcGear: 'Itens',
  bdSrcPoints: 'Pontos',
  bdSrcTree: 'Árvore',
  bdSrcAbilities: 'Habilidades',
  bdSrcTeam: 'Buffs de time',
  bdSrcAbilitiesTeam: 'Habilidades + Time',
  bdSrcHero: 'Herói',
  bdSrcAbility: 'Habilidade',
  bdNoteCapped: 'Bônus próprio + time limitado a +100%',
  bdNoteSplit: 'próprio +{own}% · time +{team}%',
  bdNoteKeenEye: 'Olho Clínico',
  bdNoteDiamondTip: 'Ponta de Diamante',
  bdNoteBrutalStrike: 'Golpe Brutal',
  bdFormulaMitF: '1 − phaseMit × (1 − pen/100)',
  bdFormulaDmg: 'abl × (1 + extra/100)',
  bdFormulaHit: 'atk × mit × dano',
  bdFormulaCriticalHit: 'hit × (1 + cd/100)',
  bdFormulaCritFactor: '1 + (cc/100) × (cd/100)',
  bdFormulaFuse: 'max(2 × (1 − cdr/100), 0.4)',
  bdFormulaBombsSerial: '1 / (pavio + caminhada)',
  bdFormulaBombsWiki: '(0.3 + 0.12 × vel × 0.0386) × sf(energia)',
  bdFormulaField: 'energia / dreno',
  bdFormulaRest: 'descansoSegundos / 60',
  bdFormulaUptime: '100 × campo / (campo + descanso)',
  bdFormulaActive: 'médio × bombas/s × (1 + 0.5 × alcance) × 0.9 × dano',
  bdFormulaSustained: 'DPSativo × (campo / (campo + descanso))',
  bdTermMit: 'Mitigação da fase (Checagem)',
  bdTermPen: 'Penetração',
  bdTermAbl: 'Mult. de dano das habilidades (ex.: 2ª explosão / execute)',
  bdTermExtra: 'Dano extra % (Checagem)',
  bdTermAtk: 'Ataque',
  bdTermMitigation: 'Fator de mitigação (linha acima)',
  bdTermDamage: 'Multiplicador de dano (linha acima)',
  bdTermCd: 'Dano Crítico',
  bdTermCc: 'Chance de Crítico',
  bdTermCdr: 'Redução de recarga',
  bdTermWalk: 'Atraso de caminhada (Checagem)',
  bdTermSf: 'Fator de soft-cap de energia',
  bdTermDrain: 'Mult. de dreno de energia (habilidades / time / Tempo)',
  bdTermRestSeconds: 'Descanso da Casa entre deploys (segundos)',
  bdTermField: 'Tempo em campo em segundos',
  bdTermRestSecs: 'Descanso em segundos (mesma janela do campo)',
  bdTermAvg: 'Hit esperado (ataque × fator de mitigação × fator de crítico)',
  bdTermRange: 'Raio da explosão (células)',
  bdTermActiveDps: 'DPS ativo',
};

export const gearPanelPtBR: GearPanelCopy = {
  fieldRequired: 'obrigatório',
  panelItems: 'Itens',
  slotStats: 'Stats por slot',
  slotStatFullLabels: {
    dmg: 'Dano',
    energia: 'Energia',
    velocidade: 'Velocidade',
    sorte: 'Sorte',
    crit: 'Chance de Crítico',
    penetracao: 'Penetração',
    cooldown: 'Redução de recarga',
  },
  gearTotals: 'Totais',
  dmgPctLabel: 'Dano (% da Ataque)',
  panelCompare: 'Comparar equipamento',
  compareTip: 'Copia seu equipamento atual para um clone editável — troque itens no clone e veja o impacto no DPS na hora.',
  compareCurrent: 'Atual',
  compareAlt: 'Clone',
  compareHit: 'Hit',
  metricSustained: 'DPS efetivo',
  copyGear: 'Copiar equipamento atual',
  reCopy: 'Copiar novamente',
  applyCompare: 'Aplicar no atual',
  clearCompare: 'Limpar',
};
