/**
 * English defaults for the two host-supplied panel contracts, so a host that prints none of this
 * vocabulary elsewhere can still draw the sheet, points, next-point, breakdown and Items panels.
 *
 * The contracts stay contracts. A host with these words already in its own dictionary — the web
 * planner, whose Stats, Points and Items screens have printed them since before this package
 * existed — keeps passing its own and is unaffected; these values are what a host without them
 * reads instead of copying 125 strings into a second dictionary that nothing keeps in sync.
 *
 * `as const` here and an annotation on the Portuguese side, the same split `en.ts`/`pt-BR.ts`
 * use. This object is checked against the contracts by the `Record<Lang, StatPanelCopy>` /
 * `Record<Lang, GearPanelCopy>` maps in `index.ts`: a member missing HERE fails to compile
 * THERE, naming it.
 */
export const statPanelEn = {
  statFull: {
    attack: 'Attack',
    energy: 'Energy',
    speed: 'Speed',
    critChance: 'Crit Chance',
    critDmg: 'Crit Damage',
    penetration: 'Penetration',
    cdr: 'Cooldown Red.',
    luck: 'Luck',
  },
  statShort: {
    attack: 'Attack',
    energy: 'Energy',
    speed: 'Speed',
    critChance: 'Crit',
    critDmg: 'Crit dmg',
    penetration: 'Pen',
    cdr: 'CDR',
    luck: 'Luck',
  },
  fieldRequired: 'required',
  colStat: 'Stat',
  panelSheet: 'Stats',
  sheetTip: "Breakdown of the in-game hero sheet as this app reads it from the running game: birth roll through level, stars, sheet abilities (Keen Eye, Diamond Tip, Brutal Strike), gear, spent points and skill tree. Total is the model's uncapped sum; when crit chance or CDR go past the game's display cap, Over cap shows how much is being wasted.",
  sheetTipNeedBirth: 'No birth roll has been read for this hero yet, so the sheet cannot be rebuilt from source. Open the game with the companion running and it will fill in.',
  colSheetBirth: 'Birth',
  colSheetDeltaLevel: 'Δ level',
  colSheetDeltaStars: 'Δ stars',
  colSheetDeltaAbility: 'Δ ability',
  colSheetDeltaGear: 'Δ gear',
  colSheetDeltaPoints: 'Δ points',
  colSheetDeltaTree: 'Δ tree',
  colSheetDeltaRune: 'Δ rune',
  colSheetTotal: 'Total',
  colSheetOverCap: 'Over cap',
  panelPoints: 'Points',
  abilitiesSpent: '{spent} / {max} points',
  pointsUnspentBanked: '+{count} unspent',
  pointsOverBudgetWarning: "These stat points don't add up: {spent} points on a level-{level} hero, and the game grants only one per level. Import a fresh save export — if it still reads this way, please report it on Discord.",
  pointsStepMinusFiveAria: 'Remove 5 points from {stat}',
  pointsStepPlusFiveAria: 'Add 5 points to {stat}',
  reset: 'Reset',
  resetAdviceGainLine: 'A fast check found a possible sustained-DPS gain of at least ~{pct}%. Optimize build on its DPS setting gives the definitive answer.',
  colPerPt: '/pt',
  colAfter: 'After',
  colPreview: 'Preview',
  metricNextPoint: 'Next point',
  rankFarmNoPool: 'Ranked on damage — no farming rotation to rank against.',
  rankFarmNoRate: 'Ranked on damage — no farmable phase for this rotation yet.',
  rankFarmAddedToPool: "This hero isn't in your farming rotation — ranked as if you added them.",
  modeDps: 'DPS',
  modeFarm: 'Farm',
  optimizeModeLabel: 'Optimize build target',
  optimizeBuildButton: 'Optimize build',
  optimizeBuildNoBudgetReason: 'No points to place at this level yet.',
  optimizeBuildBudgetExhausted: 'The search was bounded and stopped early — this is the best it found within that budget.',
  optimizeBuildHeroDisabledNote: 'This hero is disabled, so it is not included in automatic respec recommendations.',
  optimizeBuildKeptCurrent: 'This search did not beat your current allocation.',
  optimizeBuildResultLine: 'Best allocation this search found: about {pct}% more sustained DPS.',
  optimizeBuildFarmKeptCurrent: 'This search did not beat your current allocation for farming.',
  optimizeBuildFarmResultLine: 'Best allocation this search found: about {pct}% more gold per hour for your rotation.',
  optimizeBuildFarmNoPool: 'No farming rotation to search against. Add this hero to your rotation, or switch the target to DPS.',
  optimizeBuildFarmNoRate: 'No farmable phase for this rotation yet — nothing to search against.',
  previewApplyButton: 'Apply preview',
  previewClearButton: 'Clear preview',
  previewRespecNote: 'Applied on the planner — spend a real in-game reset to match this build.',
  panelEffective: 'Effective stats',
  effectiveTip:
    'Includes gear, points, skill tree, abilities and the team auras switched on below. Pack counts the heroes deployed beside this one.',
  effectiveMitF: 'Mitigation factor',
  effectiveDmg: 'Damage multiplier',
  effectiveHit: 'Hit',
  effectiveCriticalHit: 'Critical Hit',
  effectiveAvgHit: 'Average hit',
  effectiveCritFactor: 'Critical factor',
  effectiveFuse: 'Fuse',
  effectiveBombsPerSec: 'Bombs / s',
  effectiveField: 'Field time',
  effectiveRest: 'Rest',
  effectiveUptime: 'Uptime',
  effectiveActiveDps: 'Active DPS',
  effectiveSustainedDps: 'Sustained DPS',
  bdSrcBase: 'Birth roll',
  bdSrcLevel: 'Level',
  bdSrcStars: 'Stars',
  bdSrcSheetAbilities: 'Sheet abilities',
  bdSrcGear: 'Gear',
  bdSrcPoints: 'Points',
  bdSrcTree: 'Skill tree',
  bdSrcAbilities: 'Abilities',
  bdSrcTeam: 'Team auras',
  bdSrcAbilitiesTeam: 'Abilities + Team',
  bdSrcRune: 'Rune',
  bdSrcHero: 'Hero',
  bdSrcAbility: 'Ability',
  bdNoteCapped: 'Own + team bonus capped at +100%',
  bdNoteSplit: 'own +{own}% · team +{team}%',
  bdNoteKeenEye: 'Keen Eye',
  bdNoteDiamondTip: 'Diamond Tip',
  bdNoteBrutalStrike: 'Brutal Strike',
  bdNoteRune: '{hours} h of play left',
} as const;

export const gearPanelEn = {
  fieldRequired: 'required',
  panelItems: 'Items',
  slotStats: 'Stats by slot',
  gearSlotEmptyAria: '{slot} — empty',
  gearSlotEmptyTip: 'Empty',
  rankLv: 'Lv',
  slotStatFullLabels: {
    dmg: 'Damage',
    energia: 'Energy',
    velocidade: 'Speed',
    sorte: 'Luck',
    crit: 'Crit Chance',
    penetracao: 'Penetration',
    cooldown: 'Cooldown Reduction',
  },
  gearTotals: 'Totals',
  panelCompare: 'Gear compare',
  compareTip: 'Copies your current gear into an editable clone — change items on the clone and see the DPS impact instantly.',
  compareCurrent: 'Current',
  compareAlt: 'Clone',
  compareHit: 'Hit',
  metricSustained: 'Sustained DPS',
  copyGear: 'Copy current gear',
  reCopy: 'Re-copy',
  applyCompare: 'Apply to current',
  clearCompare: 'Clear',
} as const;
