/**
 * The Portuguese (Brazil) translation of `en.ts`. `HeroCopy` is a value-widening mapped type
 * (`export type HeroCopy = { readonly [K in keyof typeof heroEn]: string }` — `index.ts`), so this
 * file is annotated `: HeroCopy`, never `as HeroCopy`/`satisfies HeroCopy`/an index signature: the
 * annotation is what makes a missing key here a compile error naming the key (`TS2741`) and a
 * typo'd extra key a compile error too (`TS2353`) — both directions of the same guarantee.
 *
 * Key set and every `{placeholder}` must match `en.ts` exactly — `parity.test.ts` proves both at
 * runtime as a second, independent line of defence.
 */
import type { HeroCopy } from './index';

export const heroPtBR: HeroCopy = {
  heroDetailIdentityTitle: "Identidade",
  heroDetailIdentityRarity: "Raridade",
  heroDetailIdentityGrade: "Nota",
  heroDetailIdentityLevel: "Nível",
  heroDetailIdentityPower: "Poder",
  heroDetailIdentityMarketable: "Negociável",
  heroDetailIdentityNotMarketable: "Não negociável",
  heroDetailIdentityMarketValue: "Valor no mercado",

  heroDetailRunesTitle: "Runas",
  heroDetailRunesTip:
    "Bônus temporários que o jogo está aplicando a este herói agora. Todos os números desta tela contam com eles, e cada um some quando o tempo de jogo acaba.",
  heroDetailRuneStrength: "+{pct}%",
  heroDetailRunePlayLeft: "{hours}h de bônus restantes",
  heroDetailRuneAxisXp: "XP",
  heroDetailRuneAxisGold: "Ouro",

  heroDetailPowerTitle: "Poder",
  heroDetailPowerTip:
    "O próprio número de Poder do jogo, desmontado. Poder é dez vezes o ataque multiplicado por um fator por atributo; a fatia de cada fator é quanto dessa pilha ele levanta, medida a partir de um herói sem nada daquele atributo. O Poder é calculado antes das auras do time, então um atributo aqui pode aparecer menor que no painel de atributos efetivos.",
  heroDetailPowerPick: "Escolha um fator para ver o Poder ao longo da faixa dele.",
  heroDetailPowerDiffers: "Difere do número do jogo em {pct} (pontos estimados)",
  heroDetailPowerRunesActive: "Com as runas ativas · {value} sem elas",
  heroDetailPowerWithheld:
    "Este é o número guardado pelo jogo, sem runas. O detalhamento depende dos pontos gastos do herói, que não puderam ser lidos.",
  heroDetailPowerFactorCrit: "Crítico (chance × dano)",
  heroDetailPowerFactorSpeed: "Velocidade",
  heroDetailPowerFactorRange: "Alcance (Explosão Ampla)",
  heroDetailPowerFactorLuck: "Sorte",
  heroDetailPowerFactorEnergy: "Energia",
  heroDetailPowerFactorPenetration: "Penetração",
  heroDetailPowerFactorCooldown: "Recarga",
  heroDetailPowerFactorAttack: "Ataque",
  heroDetailPowerAnchor: "base",
  heroDetailPowerColFactor: "Fator",
  heroDetailPowerColMultiplier: "× Poder",
  heroDetailPowerColMultiplierTip:
    "Quantas vezes este fator multiplica o Poder em relação a um herói sem nada daquele atributo. A linha de Ataque mostra o próprio ataque: é a base que todo fator multiplica.",
  heroDetailPowerColShare: "Parte",
  heroDetailPowerColShareTip:
    "A parte deste fator em todo o ganho multiplicativo acima da base de Ataque. As partes somam 100%; o Ataque, a base, não tem parte.",
  heroDetailPowerShareBar: "Fatia do Poder por fator",
  heroDetailPowerSegment: "{factor}: {share}",
  heroDetailPowerAxisAmpla: "Nível de Explosão Ampla",
  heroDetailPowerChart: "Poder em função de {stat}",
  heroDetailPowerNow: "agora",
  heroDetailPowerCap: "limite",
  heroDetailPowerReadout: "{stat} {value} → Poder {power} ({delta}, {pct} em relação a agora)",
  heroDetailPowerReadoutCapped: "Com 100% de chance de crítico: {power}",
  heroDetailPowerCappedLegend: "Tracejado: com chance de crítico em 100%",
  heroDetailPowerExtrapolated: "Acima da maior recarga conferida ({pct}), isto é extrapolado.",

  heroDetailRollTitle: "Roll de nascimento",
  heroDetailRollQuality: "Qualidade do roll",
  heroDetailRollQualityNote:
    "A média dos oito percentis do roll: para cada atributo, o quanto ele avançou dentro da própria faixa. 50 é um roll mediano em tudo, 90 é perto do topo de todas as faixas.",
  heroDetailRollColStat: "Atributo",
  heroDetailRollColBand: "Faixa",
  heroDetailRollColPosition: "Posição",
  heroDetailRollValue: "Roll",
  heroDetailRollBand: "Roll dentro de {range}",
  heroDetailRollPercentile: "{pct}% dentro da faixa",
  heroDetailRollGradePlacement: "Onde ele fica na nota {letter}",
  heroDetailRollPermanent:
    "O roll de nascimento é permanente: nunca muda com nível, estrelas, equipamento ou pontos gastos.",
  heroDetailRollNoBirthRoll:
    "Este herói não tem roll de nascimento, então não há o que posicionar.",
  heroDetailRollNoBounds:
    "Este herói não tem os limites do roll, então não dá para medir a posição dentro deles.",
  heroDetailRollComputedDisagrees:
    "A qualidade que calculamos cai em uma letra diferente da que o jogo guardou.",
  heroDetailRollStoredLetterStands: "A letra guardada é a resposta do jogo e continua valendo.",
  heroDetailRollStoredLetter: "Nota guardada",
  heroDetailRollComputedLetter: "Nossa estimativa",
  heroDetailRollPlacementUncertain: "Leia a posição abaixo como incerta.",

  heroDetailAbilitiesTitle: "Habilidades",
  heroDetailAbilitiesLevelOfMax: "{level} de {max}",
  heroDetailAbilitiesEffect: "Efeito modelado",
  heroDetailAbilitiesOnSheetTag: "Na ficha",
  heroDetailAbilitiesNotModelled:
    "O modelo não tem efeito para esta habilidade, então não dá para calcular quanto ela vale.",
  heroDetailAbilitiesMaxed: "Já está no nível máximo; não existe próximo nível para comprar.",
  heroDetailAbilitiesNextLevelGain: "Mais um nível vale {pct}% para este herói",
  heroDetailAbilitiesAuraAtCeiling:
    "Seu time já está no teto desta aura em campo, então o próximo nível não compra nada.",
  heroDetailAbilitiesNotMeasured:
    "O modelo tem este efeito, mas ele cai fora do que o DPS sustentado consegue medir.",
  heroDetailAbilitiesNoBirthRoll:
    "Sem o roll de nascimento não dá para avaliar este herói, então nenhuma habilidade dele tem preço.",
  heroDetailAbilitiesPoints: "Pontos de habilidade",
  heroDetailAbilitiesPointsValue: "{spent} de {budget} gastos",
  heroDetailAbilitiesNone: "Este herói não tem nenhuma habilidade.",

  heroDetailCombatTitle: "Combate",
  heroDetailCombatNormalHit: "Hit normal",
  heroDetailCombatCritHit: "Hit crítico",
  heroDetailCombatAvgHit: "Hit médio",
  heroDetailCombatFieldTime: "Tempo em campo",
  heroDetailCombatFuseTime: "Tempo de pavio",
  heroDetailCombatUptime: "Tempo ativo",
  heroDetailCombatDps: "DPS",
  heroDetailCombatActiveDps: "DPS ativo",
  heroDetailCombatSustainedDps: "DPS sustentado",
  heroDetailCombatPenetration: "Penetração vs mitigação",
  heroDetailCombatDamageThrough: "Dano que passa",
  heroDetailCombatHitsToKill: "Hits para matar",
  heroDetailCombatProps: "Props",
  heroDetailCombatPhase: "Fase {name}",
  heroDetailCombatPhaseFromFarm: "Esta é a fase em que a sua tela de Farm está.",
  heroDetailCombatPhaseOverridden:
    "Você está vendo uma fase diferente da que está na sua tela de Farm.",
  heroDetailCombatFuseFloor: "Piso do pavio",
  heroDetailCombatFuseFloorHint: "O tempo de pavio não pode cair abaixo de {secs}s.",
  heroDetailCombatCdrCeiling: "Teto de redução de recarga",
  heroDetailCombatCdrCeilingReached: "Mais redução de recarga não compra nada.",
  heroDetailCombatNoProps: "Não há props nesta fase.",

  heroDetailPhaseTitle: "Fase a que estes números se referem",
  heroDetailPhaseLabel: "Fase",
  heroDetailPhaseAria: "Em qual fase estes números são calculados",
  heroDetailPhaseUseCurrent: "Voltar para a sua fase atual",
  heroDetailPhaseSearchPlaceholder: "Difícil, Normal 2-1 ou 151",
  heroDetailPhaseNoMatch: "Nenhuma fase corresponde.",
  heroDetailPhaseMoreMatches: "Mostrando {shown} de {matched} — continue digitando para filtrar.",

  heroDetailAurasTip:
    "Com o que os números desta etapa são precificados. Uma aura de time é uma propriedade do campo: todo mundo que está nele recebe o mesmo total, com teto por aura. A aura do próprio herói conta no rank dele e não pode ser desligada; qualquer outra aura fica desligada até você ligar, e então conta no teto, seja quem for o portador. A tela Farm e o Otimizador precificam as mesmas auras pelo tempo ativo previsto de cada portador, então os números deles podem diferir destes. A Passagem de Bastão conta aqui como se o pulso nunca acabasse — o tempo em campo inteiro no nível dela, +80% no teto — enquanto a tela Farm e o Otimizador contam só os 120 s que cada entrada acende.",
  heroDetailAurasTeamGroup: "Auras de time",
  heroDetailAuraOwnTag: "própria",
  heroDetailAuraSwitchAria: "Contar {name} no teto",
  heroDetailAuraDeltaIfOn: "+{value}% se ligada",
  heroDetailAuraDeltaIfOff: "−{value}% se desligada",

  heroDetailBreakdownHint: 'Passe o mouse ou foque um quadro para ver a fórmula por trás dele e o que ele lê; os quadros ligados a ele ficam acesos.',
  heroDetailBreakdownRowSheet: "Ficha",
  heroDetailBreakdownRowFactors: "Fatores",
  heroDetailBreakdownRowPerHit: "Por hit · cadência",
  heroDetailBreakdownRowDps: "DPS",
  heroDetailBreakdownFormulaMitF: "1 − mitigação × (1 − pen)",
  heroDetailBreakdownFormulaDmg: "matilha × extra × pulso",
  heroDetailBreakdownFormulaCritFactor: "1 + cc × dc",
  heroDetailBreakdownFormulaFuse: "max(2 × (1 − recarga), piso)",
  heroDetailBreakdownFormulaField: "energia ÷ dreno",
  heroDetailBreakdownFormulaRest: "descanso da Casa ÷ 60",
  heroDetailBreakdownFormulaHit: "atq × mitF × dano",
  heroDetailBreakdownFormulaCriticalHit: "hit × (1 + dc)",
  heroDetailBreakdownFormulaAvgHit: "hit × fator de crítico",
  heroDetailBreakdownFormulaBombs: "1 ÷ E[max(pavio, salto ÷ velocidade)]",
  heroDetailBreakdownFormulaUptime: "campo ÷ (campo + descanso)",
  heroDetailBreakdownFormulaActive: "médio × habilidades × bombas/s × espalhamento × 0.9",
  heroDetailBreakdownFormulaSustained: "ativo × aproveitamento",
  heroDetailBreakdownTermPhaseMit: "mitigação da fase",
  heroDetailBreakdownTermPenetration: "penetração",
  heroDetailBreakdownTermAbilities: "habilidades",
  heroDetailBreakdownTermPack: "matilha",
  heroDetailBreakdownTermExtra: "extra",
  heroDetailBreakdownTermPulse: "pulso, mantido",
  heroDetailBreakdownTermAttack: "ataque",
  heroDetailBreakdownTermMitF: "fator de mitigação",
  heroDetailBreakdownTermDmg: "multiplicador de dano",
  heroDetailBreakdownTermHit: "hit",
  heroDetailBreakdownTermCritChance: "chance de crítico",
  heroDetailBreakdownTermCritDmg: "dano crítico",
  heroDetailBreakdownTermCritFactor: "fator de crítico",
  heroDetailBreakdownTermCdr: "redução de recarga",
  heroDetailBreakdownTermFuseFloor: "piso",
  heroDetailBreakdownTermFuse: "pavio",
  heroDetailBreakdownTermWalk: "caminhada",
  heroDetailBreakdownTermBand: "ato",
  heroDetailBreakdownTermCycle: "ciclo",
  heroDetailBreakdownTermEnergy: "energia",
  heroDetailBreakdownTermDrain: "dreno",
  heroDetailBreakdownTermRestSeconds: "descanso",
  heroDetailBreakdownTermField: "tempo em campo",
  heroDetailBreakdownTermAvgHit: "hit médio",
  heroDetailBreakdownTermBombs: "bombas/s",
  heroDetailBreakdownTermRangeMult: "espalhamento da explosão",
  heroDetailBreakdownTermAiEfficiency: "eficiência da IA",
  heroDetailBreakdownTermActiveDps: "DPS ativo",
  heroDetailBreakdownReads: "Lê",
  heroDetailBreakdownNoteFuseAtCeiling:
    "No teto: o pavio não desce de {floor}s, então redução de recarga acima de {cap}% não compra nada.",
  heroDetailBreakdownNoteFuseFloor:
    "O pavio não desce de {floor}s; a redução de recarga para de pagar em {cap}%.",
  heroDetailBreakdownNoteAvgHitEqualsHit: "Igual ao Hit: a chance de crítico é zero, então nenhum hit é crítico.",
  heroDetailBreakdownNoteHitWithoutExpectedBlasts:
    "O que uma explosão mostra no jogo. {names} soma dano que nenhuma explosão isolada mostra, então fica de fora aqui; o DPS ativo carrega isso como ×{mult}.",
  heroDetailBreakdownNoteFieldWithoutTeamDrain: "Sem o {name} do time isto seria {secs}s.",
  heroDetailBreakdownNoteActiveConstants:
    "O espalhamento da explosão é 1 + 0,5 por célula de alcance ({cells} células aqui): cada célula além do epicentro alcança em média meio hit de props. O alcance é sempre em células inteiras — Explosão Ampla o sobe nos níveis 10 e 20. A eficiência da IA é o ×0,9 fixo do jogo para o remirar e as bombas mal colocadas de um herói em campo; todo DPS ativo deste app carrega isso.",
  heroDetailBreakdownNoteBatonHeld:
    "A Passagem de Bastão conta como se o pulso nunca acabasse: o tempo em campo inteiro a +{pct}%. A página Farm e o Otimizador contam só os 120 s que cada entrada acende.",
  heroDetailBreakdownPenCovers: "nada perdido para a mitigação",
  heroDetailBreakdownPenShort: "{lost}% de cada hit perdido para a mitigação",
  heroDetailBreakdownNotePenPierced: "A penetração está em 100%, então a mitigação da fase não tira nada do hit.",
  heroDetailBreakdownNotePenPartial:
    "A penetração atravessa uma fração da mitigação da fase, não pontos dela: {pen}% dos {mit}% da fase são atravessados, então {lost}% de cada hit ainda se perde. Só 100% de penetração não perde nada.",
  heroDetailBreakdownIconOff: "{name} — desligada",
  heroDetailBreakdownMatrixTitle: "Atributos da ficha",
  heroDetailBreakdownColStat: "Atributo",
  heroDetailBreakdownColHero: "Herói",
  heroDetailBreakdownColGear: "Itens",
  heroDetailBreakdownColAbility: "Habilidade",
  heroDetailBreakdownColTree: "Árvore",
  heroDetailBreakdownColRune: "Runa ×",
  heroDetailBreakdownColSheetTotal: "Total da ficha",
  heroDetailBreakdownColAura: "Aura ×",
  heroDetailBreakdownColEffective: "Efetivo",
  heroDetailBreakdownAuraOff: "desl.",
  heroDetailBreakdownHeroCellAria: "Como o valor de herói de {stat} é montado",

  heroDetailSheetTitle: "Ficha de atributos",
  heroDetailPointsTitle: "Pontos gastos",
  heroDetailBreakdownTitle: "Detalhe por atributo",
  heroDetailGearTitle: "Conjunto equipado",
  heroDetailGearSlotContribution: "Contribuição por espaço",
  heroDetailGearTotals: "Totais do equipamento",
  heroDetailGearCompareTitle: "Comparação de conjuntos",
  heroDetailNextStatTitle: "Próximo atributo recomendado",
  heroDetailNextStatModeDamage: "Dano",
  heroDetailNextStatModeFarming: "Farm",
  heroDetailNextStatFarmUnavailable: "A recomendação de farm não está disponível aqui: {reason}",

  heroDetailEmptyNoAccount: "O jogo não está aberto, ou a conta ainda não foi lida.",
  heroDetailEmptyNoHeroes: "Esta conta não tem nenhum herói.",
};
