import type { ShareCardCopy } from './share-card-copy';

export const shareCardEn: ShareCardCopy = {
  openButton: 'Share',
  dialogTitle: 'Share your roster',
  dialogClose: 'Close',
  brand: 'Bomb Farm Companion',
  fallbackTitle: 'My squad',
  accountNumber: 'Account #{id}',
  currentPhase: 'Current phase {phase}',
  maxPhase: 'Max phase {phase}',
  separator: ' · ',
  totalPower: 'Total power',
  heroCount: '{count} heroes',
  heroCountOne: '1 hero',
  tierCount: '{count} {rarity}',
  medalPower: ['Strongest', '2nd', '3rd'],
  dps: '{dps} DPS',
  rarityLevel: '{rarity} · Lv {level}',
  aurasTitle: 'Team auras · {covered} of {total}',
  auraLevel: '{level}/{max}',
  auraMissing: 'Not on the team',
  restTitle: 'Also on the team',
  footerSnapshot: 'Snapshot from the desktop app · DPS at phase {phase}',
  footerLink: '{host}/download',
  cardLabel: 'Your share card',
  emptyCard: 'Pick at least one hero to put on the card.',
  phaseTitle: 'Current phase (DPS is worked out here)',
  phaseAria: 'Phase',
  phaseReset: 'Use my current phase ({phase})',
  pickerTitle: 'Heroes on the card · {count}',
  pickSquad: 'Squad only',
  pickEveryone: 'Everyone',
  pickNone: 'Clear',
  pickerFilterLabel: 'Filter the list by hero name',
  pickerFilterPlaceholder: 'Filter by name',
  pickerRarityLabel: 'Filter the list by rarity',
  pickerNoMatch: 'No hero matches the filter.',
  pickerLevel: 'Lv {level}',
  showTitle: 'Show',
  showGear: 'Gear on featured heroes',
  showAuras: 'Team auras',
  showAccountNumber: 'My account number',
  shareTitle: 'Share',
  copyImage: 'Copy as image',
  copying: 'Making the image…',
  copied: 'Copied',
  copyFailed: 'The image could not be copied. Try again.',
};
