import type { ShareCardCopy } from './share-card-copy';

export const shareCardPtBR: ShareCardCopy = {
  openButton: 'Compartilhar',
  dialogTitle: 'Compartilhe seu elenco',
  dialogClose: 'Fechar',
  brand: 'Bomb Farm Companion',
  fallbackTitle: 'Meu esquadrão',
  accountNumber: 'Conta #{id}',
  currentPhase: 'Fase atual {phase}',
  maxPhase: 'Fase máxima {phase}',
  separator: ' · ',
  totalPower: 'Poder total',
  heroCount: '{count} heróis',
  heroCountOne: '1 herói',
  tierCount: '{count} {rarity}',
  medalPower: ['Mais forte', '2º', '3º'],
  medalRoll: ['Melhor sorteio', '2º melhor sorteio', '3º melhor sorteio'],
  dps: '{dps} DPS',
  rarityLevel: '{rarity} · Nv {level}',
  aurasTitle: 'Auras de time · {covered} de {total}',
  auraLevel: '{level}/{max}',
  auraMissing: 'Fora do time',
  restTitle: 'Também no time',
  footerSnapshot: 'Retrato do app de desktop · DPS na fase {phase}',
  footerLink: '{host}/download',
  cardLabel: 'Seu cartão para compartilhar',
  emptyCard: 'Escolha pelo menos um herói para pôr no cartão.',
  featureTitle: 'Destaque',
  featurePower: 'Os três mais fortes',
  featureRoll: 'Melhores sorteios de nascimento',
  phaseTitle: 'Fase atual (o DPS é calculado nela)',
  phaseAria: 'Fase',
  phaseIncrement: 'Próxima fase',
  phaseDecrement: 'Fase anterior',
  phaseReset: 'Usar minha fase atual ({phase})',
  pickerTitle: 'Heróis no cartão · {count}',
  pickSquad: 'Só o esquadrão',
  pickEveryone: 'Todos',
  pickNone: 'Limpar',
  pickerLevel: 'Nv {level}',
  showTitle: 'Mostrar',
  showGear: 'Equipamento dos destaques',
  showAuras: 'Auras de time',
  showAccountNumber: 'Meu número de conta',
  shareTitle: 'Compartilhar',
  copyImage: 'Copiar como imagem',
  copying: 'Gerando a imagem…',
  copied: 'Copiado — cole numa conversa',
  copyFailed: 'Não foi possível copiar a imagem. Tente de novo.',
};
