export const showcaseEn = {
  typeCrit: 'Crit striker',
  typeHeavy: 'Heavy hitter',
  typePierce: 'Piercer',
  typeFinish: 'Finisher',
  typeGate: 'Gate hunter',
  typeLoot: 'Looter',
  typeBuff: 'Squad buffer',
  typeEndure: 'Endurance',
  typeNone: 'Unspecialised',
  highestRolls: 'Highest rolls: {rolls}',
  highestRollEntry: '{stat} {pct}',
  highestRollsSeparator: ', ',
  rollStat: {
    attack: 'ATK',
    energy: 'Energy',
    speed: 'Speed',
    luck: 'Luck',
    critChance: 'Crit Chance',
    critDmg: 'Crit DMG',
    penetration: 'PEN',
    cdr: 'CDR',
  },
  summaryTitle: 'Roster summary',
  summarySquadPower: 'Squad power',
  summaryTopHeroes: 'Top heroes',
  summaryRarityMix: 'Rarity mix',
  summaryMaxPhase: 'Max phase',
  summaryAverageItemLevel: 'Average item level',
  summaryAverageForge: 'Average forge',
  summarySquadCount: '{count} in squad',
  summaryBenchCount: '{count} on bench',
  summaryHeroes: 'Heroes',
  summaryRarityEntry: '{count} {rarity}',
  summarySquadGear: 'Squad gear, average',
  summaryGearAverages: 'Lv {level} · forged +{forge}',
  summaryGearItems: 'across {count} equipped items',
  cardPosition: '#{position}',
  cardPower: 'Power',
  cardLevel: 'Level {level}',
  cardBirthGrade: 'Birth grade {grade}',
  cardBirthRoll: 'Birth roll {pct}',
  cardWideBlast: '{ability} ✓',
  cardAverageItemLevel: 'Average item level {level} · +{forge}',
  cardNothingEquipped: 'Nothing equipped',
  aurasTitle: 'Team auras',
  aurasCovered: '{covered} of {total}',
  auraLevel: 'Lv {level}/{max}',
  auraNoCarrier: 'Nobody carries it',
  columnPosition: '#',
  columnName: 'Hero',
  columnRarity: 'Rarity',
  columnLevel: 'Level',
  columnBirth: 'Birth',
  columnPower: 'Power',
  columnAttack: 'Attack',
  columnCritChance: 'Crit chance',
  columnCritDmg: 'Crit damage',
  columnLuck: 'Luck',
  columnSpeed: 'Speed',
  columnAbilities: 'Abilities',
  columnGear: 'Gear',
  filterEveryone: 'Everyone',
  filterSquad: 'Squad',
  filterBench: 'Bench',
} as const;
