import type { ShowcaseCopy } from './showcase-copy';

export const showcasePtBR: ShowcaseCopy = {
  typeCrit: 'Atacante crítico',
  typeHeavy: 'Dano pesado',
  typePierce: 'Perfurador',
  typeFinish: 'Finalizador',
  typeGate: 'Caçador de portões',
  typeLoot: 'Saqueador',
  typeBuff: 'Suporte do esquadrão',
  typeEndure: 'Resistente',
  typeNone: 'Sem especialidade',
  rollStat: {
    attack: 'ATK',
    energy: 'Energia',
    speed: 'Velocidade',
    luck: 'Sorte',
    critChance: 'Chance crít.',
    critDmg: 'Dano crít.',
    penetration: 'PEN',
    cdr: 'CDR',
  },
  summaryTitle: 'Resumo do elenco',
  summarySquadPower: 'Poder do esquadrão',
  summaryRarityMix: 'Raridades',
  summaryMaxPhase: 'Fase máxima',
  summaryAverageItemLevel: 'Nível médio dos itens',
  summaryAverageForge: 'Forja média',
  summarySquadCount: '{count} no esquadrão',
  summaryBenchCount: '{count} no banco',
  summaryHeroes: 'Heróis',
  summaryRarityEntry: '{count} {rarity}',
  summarySquadGear: 'Equipamento do esquadrão, média',
  summaryGearAverages: 'Nv {level} · forjado +{forge}',
  summaryGearItems: 'em {count} itens equipados',
  summaryGearRange: 'itens Nv {lowest}–{highest}',
  cardPosition: '#{position}',
  cardPower: 'Poder',
  cardLevel: 'Nível {level}',
  cardBirthGrade: 'Nota de nascimento {grade}',
  cardBirthSection: 'Nascimento',
  cardBirthOverall: 'Geral',
  cardHighestRollsHeading: 'Pontos fortes',
  cardRollRangeHint: '% da faixa',
  cardShowLevels: 'Mostrar níveis',
  cardGearAverage: 'Média',
  cardGearLevel: 'Nv {level}',
  cardGearForge: 'Forja',
  cardNothingEquipped: 'Nada equipado',
  aurasTitle: 'Auras de time',
  aurasCovered: '{covered} de {total}',
  auraLevel: 'Nv {level}/{max}',
  auraNoCarrier: 'Ninguém tem',
  columnPosition: '#',
  columnName: 'Herói',
  columnRarity: 'Raridade',
  columnLevel: 'Nível',
  columnBirth: 'Nascimento',
  columnPower: 'Poder',
  columnAttack: 'Ataque',
  columnEnergy: 'Energia',
  columnPenetration: 'Penetração',
  columnCdr: 'Redução de recarga',
  columnCritChance: 'Chance crít.',
  columnCritDmg: 'Dano crít.',
  columnLuck: 'Sorte',
  columnSpeed: 'Velocidade',
  columnAbilities: 'Habilidades',
  columnGear: 'Equipamento',
  filterEveryone: 'Todos',
  filterSquad: 'Esquadrão',
  filterBench: 'Banco',
  tableFilterLabel: 'Quais heróis',
  tableLabel: 'Ranking de heróis',
  tableHint: 'Clique numa coluna para ordenar e numa linha para abrir o herói.',
  tableEmpty: 'Nenhum herói aqui.',
  tableGear: '{count}/{slots} · Nv {level}',
  tableColumns: 'Colunas',
  tableColumnsShown: 'Colunas exibidas',
  tableColumnsShowAll: 'Mostrar todas',
  tableColumnsHideAll: 'Ocultar todas',
  tableColumnsSearch: 'Buscar coluna',
  tableColumnsEmpty: 'Nenhuma coluna corresponde.',
};
