import type { ShowcaseCopy } from './showcase-copy';

export const showcasePtBR: ShowcaseCopy = {
  typeCrit: 'Crítico',
  typeHeavy: 'Pesado',
  typePierce: 'Perfurador',
  typeFinish: 'Finalizador',
  typeGate: 'Caçador de portões',
  typeLoot: 'Saqueador',
  typeBuff: 'Suporte do esquadrão',
  typeEndure: 'Resistente',
  typeNone: 'Sem especialidade',
  highestRolls: 'Melhores rolls: {rolls}',
  highestRollEntry: '{stat} {pct}',
  highestRollsSeparator: ', ',
  rollStat: {
    attack: 'ATK',
    energy: 'Energia',
    speed: 'Velocidade',
    luck: 'Sorte',
    critChance: 'Chance crít.',
    critDmg: 'Dano crít.',
    penetration: 'PEN',
    cdr: 'CDR',
  },
  summarySquadPower: 'Poder do esquadrão',
  summaryTopHeroes: 'Melhores heróis',
  summaryRarityMix: 'Raridades',
  summaryMaxPhase: 'Fase máxima',
  summaryAverageItemLevel: 'Nível médio dos itens',
  summaryAverageForge: 'Forja média',
  summarySquadCount: '{count} no esquadrão',
  summaryBenchCount: '{count} no banco',
  aurasTitle: 'Auras de time',
  aurasCovered: '{covered} de {total}',
  auraLevel: 'Nv {level}/{max}',
  auraNoCarrier: 'Ninguém tem',
  columnPosition: '#',
  columnName: 'Herói',
  columnRarity: 'Raridade',
  columnLevel: 'Nível',
  columnBirth: 'Nascimento',
  columnPower: 'Poder',
  columnAttack: 'Ataque',
  columnCritChance: 'Chance crít.',
  columnCritDmg: 'Dano crít.',
  columnLuck: 'Sorte',
  columnSpeed: 'Velocidade',
  columnAbilities: 'Habilidades',
  columnGear: 'Equipamento',
  filterEveryone: 'Todos',
  filterSquad: 'Esquadrão',
  filterBench: 'Banco',
};
