/**
 * The ledger of what changed since a plan was computed: one row per change, before and after,
 * and whether the plan cares. Split out because the rows are read as a set — the verdict words,
 * the group titles and the field names have to agree with each other — and because a row's field
 * name is a fragment ("levelled", "forged") that reads wrong anywhere but in this table.
 */
export const teamPlanChangesEn = {
  teamPlanChangesTitle: 'Since this plan was computed',
  teamPlanChangesCountOne: '1 change the plan cares about',
  teamPlanChangesCountMany: '{n} changes the plan cares about',
  teamPlanChangesRecompute: 'Build team plan again',
  teamPlanChangesKeep: 'Keep this plan',
  teamPlanChangesGroupPlan: 'Changes the plan',
  teamPlanChangesGroupProgress: 'Progress on this plan',
  teamPlanChangesGroupNoise: 'Not counted',
  teamPlanChangesRotationOne: '1 hero rotated on or off the field — the plan does not depend on that',
  teamPlanChangesRotationMany: '{n} heroes rotated on or off the field — the plan does not depend on that',
  teamPlanChangesColWhat: 'What',
  teamPlanChangesColChange: 'Change',
  teamPlanChangesColBeforeNow: 'Before → now',
  teamPlanChangesColVerdict: 'Verdict',
  teamPlanChangesAsked: 'plan asked {value}',
  teamPlanChangesAskedDone: 'as planned',
  teamPlanChangesNobody: 'nobody',
  teamPlanChangesOn: 'on',
  teamPlanChangesOff: 'off',
  teamPlanChangesSubjectAccount: 'Account',
  teamPlanChangesSubjectSetup: 'Setup',
  teamPlanChangesHeroAdded: 'new on the roster',
  teamPlanChangesHeroRemoved: 'gone from the roster',
  teamPlanChangesLevel: 'levelled',
  teamPlanChangesStars: 'stars',
  teamPlanChangesPoints: 'points in {stat}',
  teamPlanChangesPointsAvailable: 'points to spend',
  teamPlanChangesAbility: '{ability} level',
  teamPlanChangesRuneGained: 'rune appeared · {axis} +{pct}%',
  teamPlanChangesRuneLost: 'rune expired · {axis} +{pct}%',
  teamPlanChangesHeroOther: 'sheet changed',
  teamPlanChangesItemAdded: 'new in the bag',
  teamPlanChangesItemRemoved: 'gone from the bag',
  teamPlanChangesForge: 'forged',
  teamPlanChangesEquippedBy: 'equipped by',
  teamPlanChangesItemOther: 'piece changed',
  teamPlanChangesTree: 'skill tree · {axis}',
  teamPlanChangesTreeTeamCoin: 'Team coin',
  teamPlanChangesXp: 'XP',
  teamPlanChangesRuneAxisGold: 'Gold',
  teamPlanChangesFieldHouseIdx: 'house',
  teamPlanChangesFieldHouseLevel: 'house level',
  teamPlanChangesFieldPhase: 'farming phase',
  teamPlanChangesFieldMaxPhase: 'highest phase',
  teamPlanChangesFieldSlots: 'house slots',
  teamPlanChangesFieldFieldSlots: 'field slots',
  teamPlanChangesFieldHouseCycleSecs: 'house cycle, seconds',
  teamPlanChangesControlForgeFloor: 'forge floor',
  teamPlanChangesControlObjective: 'objective',
  teamPlanChangesControlAllowedChanges: 'allowed changes',
  teamPlanChangesControlIgnoreFieldCrowding: 'keep every hero geared',
  teamPlanChangesControlAurasAtCap: 'auras at cap',
  teamPlanChangesControlTargetPhase: 'phase scored at',
  teamPlanChangesScope: 'scope of {hero}',
} as const;
