import type { TeamPlanChangesCopy } from './index';

export const teamPlanChangesPtBR: TeamPlanChangesCopy = {
  teamPlanChangesTitle: 'Sua conta mudou desde que este plano foi montado',
  teamPlanChangesCountOne: '1 mudança quebra o plano',
  teamPlanChangesCountMany: '{n} mudanças quebram o plano',
  teamPlanChangesRecompute: 'Montar plano do time de novo',
  teamPlanChangesGroupBreaks: 'Quebra o plano',
  teamPlanChangesColWhat: 'O quê',
  teamPlanChangesColChange: 'Mudança',
  teamPlanChangesColBeforeNow: 'Antes → agora',
  teamPlanChangesColVerdict: 'Veredito',
  teamPlanChangesAsked: 'o plano pediu {value}',
  teamPlanChangesAskedDone: 'como planejado',
  teamPlanChangesOn: 'ligado',
  teamPlanChangesOff: 'desligado',
  teamPlanChangesSubjectAccount: 'Conta',
  teamPlanChangesSubjectSetup: 'Configuração',
  teamPlanChangesHeroAdded: 'novo no elenco',
  teamPlanChangesHeroRemoved: 'saiu do elenco',
  teamPlanChangesHeroRemovedUsed: 'saiu do elenco — o plano contava com este herói',
  teamPlanChangesLevel: 'subiu de nível',
  teamPlanChangesStars: 'estrelas',
  teamPlanChangesPoints: 'pontos em {stat}',
  teamPlanChangesPointsAvailable: 'pontos para gastar',
  teamPlanChangesAbility: 'nível de {ability}',
  teamPlanChangesRuneGained: 'runa apareceu · {axis} +{pct}%',
  teamPlanChangesRuneLost: 'runa expirou · {axis} +{pct}%',
  teamPlanChangesHeroOther: 'ficha mudou',
  teamPlanChangesItemAdded: 'novo na bolsa',
  teamPlanChangesItemRemoved: 'saiu da bolsa',
  teamPlanChangesItemRemovedUsed: 'saiu da bolsa — o plano usava esta peça',
  teamPlanChangesForge: 'forjado',
  teamPlanChangesEquippedBy: 'equipado por',
  teamPlanChangesMovedToInventory: 'movido para o inventário',
  teamPlanChangesInventory: 'Inventário',
  teamPlanChangesItemOther: 'peça mudou',
  teamPlanChangesTree: 'árvore · {axis}',
  teamPlanChangesTreeTeamCoin: 'Moeda do time',
  teamPlanChangesXp: 'XP',
  teamPlanChangesRuneAxisGold: 'Ouro',
  teamPlanChangesFieldHouseIdx: 'casa',
  teamPlanChangesFieldHouseLevel: 'nível da casa',
  teamPlanChangesFieldPhase: 'fase de farm',
  teamPlanChangesFieldMaxPhase: 'fase mais alta',
  teamPlanChangesFieldSlots: 'vagas na casa',
  teamPlanChangesFieldFieldSlots: 'vagas no campo',
  teamPlanChangesFieldHouseCycleSecs: 'ciclo da casa, segundos',
  teamPlanChangesControlForgeFloor: 'piso da forja',
  teamPlanChangesControlObjective: 'objetivo',
  teamPlanChangesControlAllowedChanges: 'o que mudar',
  teamPlanChangesControlIgnoreFieldCrowding: 'manter todos equipados',
  teamPlanChangesControlAurasAtCap: 'auras no teto',
  teamPlanChangesControlTargetPhase: 'fase pontuada',
  teamPlanChangesScope: 'escopo de {hero}',
};
