import type { TeamPlanChangesCopy } from './index';

export const teamPlanChangesPtBR: TeamPlanChangesCopy = {
  teamPlanChangesTitle: 'Desde que este plano foi montado',
  teamPlanChangesCountOne: '1 mudança que pesa no plano',
  teamPlanChangesCountMany: '{n} mudanças que pesam no plano',
  teamPlanChangesRecompute: 'Montar plano do time de novo',
  teamPlanChangesKeep: 'Manter este plano',
  teamPlanChangesGroupPlan: 'Muda o plano',
  teamPlanChangesGroupProgress: 'Progresso neste plano',
  teamPlanChangesGroupNoise: 'Não conta',
  teamPlanChangesRotationOne: '1 herói entrou ou saiu do campo — o plano não depende disso',
  teamPlanChangesRotationMany: '{n} heróis entraram ou saíram do campo — o plano não depende disso',
  teamPlanChangesColWhat: 'O quê',
  teamPlanChangesColChange: 'Mudança',
  teamPlanChangesColBeforeNow: 'Antes → agora',
  teamPlanChangesColVerdict: 'Veredito',
  teamPlanChangesAsked: 'o plano pediu {value}',
  teamPlanChangesAskedDone: 'como planejado',
  teamPlanChangesNobody: 'ninguém',
  teamPlanChangesOn: 'ligado',
  teamPlanChangesOff: 'desligado',
  teamPlanChangesSubjectAccount: 'Conta',
  teamPlanChangesSubjectSetup: 'Configuração',
  teamPlanChangesHeroAdded: 'novo no elenco',
  teamPlanChangesHeroRemoved: 'saiu do elenco',
  teamPlanChangesLevel: 'subiu de nível',
  teamPlanChangesStars: 'estrelas',
  teamPlanChangesPoints: 'pontos em {stat}',
  teamPlanChangesPointsAvailable: 'pontos para gastar',
  teamPlanChangesAbility: 'nível de {ability}',
  teamPlanChangesRuneGained: 'runa apareceu · {axis} +{pct}%',
  teamPlanChangesRuneLost: 'runa expirou · {axis} +{pct}%',
  teamPlanChangesHeroOther: 'ficha mudou',
  teamPlanChangesItemAdded: 'novo na bolsa',
  teamPlanChangesItemRemoved: 'saiu da bolsa',
  teamPlanChangesForge: 'forjado',
  teamPlanChangesEquippedBy: 'equipado por',
  teamPlanChangesItemOther: 'peça mudou',
  teamPlanChangesTree: 'árvore · {axis}',
  teamPlanChangesTreeTeamCoin: 'Moeda do time',
  teamPlanChangesXp: 'XP',
  teamPlanChangesRuneAxisGold: 'Ouro',
  teamPlanChangesFieldHouseIdx: 'casa',
  teamPlanChangesFieldHouseLevel: 'nível da casa',
  teamPlanChangesFieldPhase: 'fase de farm',
  teamPlanChangesFieldMaxPhase: 'fase mais alta',
  teamPlanChangesFieldSlots: 'vagas na casa',
  teamPlanChangesFieldFieldSlots: 'vagas no campo',
  teamPlanChangesFieldHouseCycleSecs: 'ciclo da casa, segundos',
  teamPlanChangesControlForgeFloor: 'piso da forja',
  teamPlanChangesControlObjective: 'objetivo',
  teamPlanChangesControlAllowedChanges: 'mudanças permitidas',
  teamPlanChangesControlIgnoreFieldCrowding: 'manter todos equipados',
  teamPlanChangesControlAurasAtCap: 'auras no teto',
  teamPlanChangesControlTargetPhase: 'fase pontuada',
  teamPlanChangesScope: 'escopo de {hero}',
};
