/**
 * The Portuguese (Brazil) translation of `en.ts`. `Copy` is a value-widening
 * mapped type (`export type Copy = { readonly [K in keyof typeof en]: string }` — `index.ts`), so
 * this file is annotated `: Copy`, never `as Copy`/`satisfies Copy`/an index signature: the
 * annotation is what makes a missing key here a compile error naming the key (`TS2741`) and a
 * typo'd extra key a compile error too (`TS2353`) — both directions of the same compile-time guarantee.
 *
 * Key set and every `{placeholder}` must match `en.ts` exactly — `parity.test.ts` proves both at
 * runtime as a second, independent line of defence (a future widening of `Copy` must not silently
 * disable the compile-time proof). Natural PT-BR at the concept level, not word-for-word English
 * calques (`docs/i18n.md`, "Portuguese chrome quality"); no invented aliases for official in-game
 * names (those come from `@bombfarm/domain/game-labels` — this file carries none).
 */
import type { Copy } from './index';

export const ptBR: Copy = {
  // shell* — AppShell navigation and status chrome
  gameConnected: 'Conectado',
  gameStale: 'Parado',
  gameNotRunning: 'Fechado',
  gameConnecting: 'Conectando',
  gameFeedStaleTip: 'O jogo está aberto, mas nada chega dele há {age}',
  gameFeedStaleNoAgeTip: 'O jogo está aberto, mas nada está chegando dele',
  gameFeedNotRunningTip: 'Nenhum processo do jogo encontrado — o app continua procurando sozinho',
  shellLoadingLabel: 'Carregando…',
  shellUpdateAvailable: 'Atualização disponível',
  shellUpdateDownloading: 'Atualizando… {percent}%',
  shellUpdateReady: 'Reinicie para atualizar',
  shellUpdateOpenSettings: 'Abrir as configurações de atualização',
  feedsAccount: 'Conta',
  feedsPvp: 'PVP',
  feedsPrices: 'Preços',
  feedsUpdates: 'Atualizações',
  feedsRefreshAll: 'Atualizar todos os feeds, um de cada vez',
  feedsRefreshAllStep: '{step}/{total}',
  feedsRefreshOne: 'Atualizar {feed} agora',
  feedsWhatAccount: 'Seus heróis, bolsa, árvore e casa, lidos do jogo',
  feedsWhatPvp: 'Sua posição no PVP e o ranking de pontos',
  feedsWhatPrices: 'A lista de preços do mercado',
  feedsWhatUpdates: 'Se há uma versão mais nova deste app',
  feedsLastRead: 'Última leitura {age}',
  feedsNeverRead: 'Ainda não lido',
  feedsReadingNow: 'Lendo agora…',
  feedsOutOfDate: 'Desatualizado — esta tela foi calculada com uma cópia mais antiga da conta',
  feedsNoClock: 'Lido quando a aba abre, e a cada duelo',
  feedsClickToUpdate: 'Clique para atualizar agora',
  feedsUpdatesOff: 'Esta versão não procura atualizações — as versões Beta e estável instaladas procuram',
  feedsUpdatesBusy: 'Uma atualização já está a caminho — veja em Configurações',
  feedsNextIn: 'próxima em {age}',
  feedsNextDue: 'pendente agora',
  feedsEvery: 'a cada {cycle}',
  feedsRefused: 'recusado',
  feedsCycleMinutes: '{n} min',
  shellCoffeeLabel: 'Me pague um café',
  shellMoreActionsLabel: 'Mais ações',
  shellReferralMenuLabel: 'Copiar código de indicação',
  shellReferralLabel:
    'Copiar meu código de indicação — nós dois ganhamos uma recompensa quando você passar da fase 151',
  shellReferralCopied: 'Código de indicação copiado',
  shellReferralCopyManual:
    'Área de transferência indisponível — o código está selecionado, aperte Control e C para copiar.',

  // empty* — placeholder states shown before real data has arrived
  emptyBridgeUnavailableTitle: 'Ponte de comunicação indisponível',
  valueNotAvailable: 'não disponível',

  // account* — the shared account-read states every data screen shows
  accountLoadingTitle: 'Carregando sua conta…',

  // error* — failure paths
  errorAccountReadFailed: 'Não foi possível ler a conta',

  // age* — relative-age words for format.ts. Singular/plural-agnostic by construction, matching
  // en.ts's own constraint — 'há {n}m' reads naturally for every n.
  ageJustNow: 'agora mesmo',
  ageMinutes: 'há {n}m',
  ageHours: 'há {n}h',
  ageDays: 'há {n}d',
  // 's' for seconds is the same abbreviation in PT-BR as in English — a legitimately identical
  // pair, declared in index.ts's IDENTICAL_IN_BOTH_LANGUAGES table rather than left to look like
  // an untranslated leftover.
  ageShortSeconds: '{n}s',
  ageShortMinutes: '{n}min',

  // settings* — the language control
  settingsNavLabel: 'Configurações',
  settingsLanguageSectionTitle: 'Idioma',
  settingsLanguageLabel: 'Idioma do aplicativo',
  settingsLanguageHelp: 'As mudanças têm efeito imediato.',
  settingsLanguageOptionEnglish: 'Inglês',
  settingsLanguageOptionPortuguese: 'Português (Brasil)',
  settingsLanguageNotSavedTitle: 'Idioma alterado, mas não salvo',
  settingsLanguageReasonNoStore:
    'Seu local de salvamento está indisponível, então isso não vai sobreviver a um reinício.',
  settingsLanguageReasonNotWritable:
    'Seu local de salvamento não pode ser gravado, então isso não vai sobreviver a um reinício.',
  settingsLanguageReasonUnknown: 'Essa escolha não pôde ser salva, então não vai sobreviver a um reinício.',

  settingsWindowSectionTitle: 'Janela',
  settingsAlwaysOnTopMainLabel: 'Manter a janela principal no topo',
  settingsAlwaysOnTopMainHelp:
    'O companion fica acima das outras janelas enquanto isso estiver ligado. Tem efeito imediato.',
  settingsAlwaysOnTopNotSavedTitle: 'Sempre no topo alterado, mas não salvo',
  settingsAlwaysOnTopMiniLabel: 'Manter a janela compacta no topo',
  settingsAlwaysOnTopMiniHelp:
    'A janela compacta do Ao vivo fica acima das outras janelas enquanto isso estiver ligado. Tem efeito imediato.',
  settingsAlwaysOnTopMiniNotSavedTitle: 'Sempre no topo da janela compacta alterado, mas não salvo',

  // settingsForge* — o único interruptor que deixa a aba Forja gastar ouro (desligado por padrão)
  settingsForgeSectionTitle: 'Forja',
  settingsForgeWritesLabel: 'Deixar a Forja gastar ouro',
  settingsForgeWritesHelp:
    'Desligado: a aba Forja planeja subidas e nunca rola. Ligado: o botão Forjar gasta ouro da sua conta, uma execução confirmada por vez.',
  settingsForgeWritesNotSavedTitle: 'Configuração da Forja alterada, mas não salva',

  // settingsGame*/settingsRestartGameOnExit* — o único interruptor que deixa a Steam trazer o
  // jogo de volta depois que ele fecha (desligado por padrão)
  settingsGameSectionTitle: 'Jogo',
  settingsRestartGameOnExitLabel: 'Reiniciar o Bomb Farm se ele fechar',
  settingsRestartGameOnExitHelp:
    'Com isto ligado, se o jogo fechar enquanto o companion já está aberto, a Steam inicia-o de novo. O companion não inicia o jogo ao abrir. Desligado por padrão.',
  settingsRestartGameOnExitNotSavedTitle: 'Configuração do jogo alterada, mas não salva',

  // settingsMarket* — a moeda que este app pede à Steam ao atualizar o preço de um item
  settingsMarketSectionTitle: 'Mercado',
  settingsMarketQuoteCurrencyLabel: 'Moeda dos preços atualizados',
  settingsMarketQuoteCurrencyHelp:
    'Ao atualizar um item, a Steam é consultada nesta moeda. A lista de preços compartilhada continua convertida do dólar.',
  settingsMarketQuoteCurrencySearchPlaceholder: 'USD, Euro ou Real',
  settingsMarketQuoteCurrencyNoMatch: 'Nenhuma moeda corresponde.',
  settingsMarketQuoteCurrencyNotSavedTitle: 'Moeda alterada, mas não salva',

  // settingsConsent* — o controle de revogar o acesso à conta (Configurações só é alcançável já permitido)
  settingsConsentSectionTitle: 'Acesso à conta',
  settingsConsentStatusGranted: 'Acesso: permitido',
  settingsConsentHelpGranted: 'O companion lê sua conta e permanece conectado ao cliente do jogo.',
  settingsConsentRevokeAction: 'Desativar',

  // settingsDiagnostics* — o controle manual de gravação do anel de quadros (um recurso de relatório de erro)
  settingsDiagnosticsSectionTitle: 'Diagnóstico',
  settingsDiagnosticsSaveLabel: 'Salvar arquivo para relatório de erro',
  settingsDiagnosticsSaveHelp:
    'Grava um arquivo local com detalhes do tráfego recente do jogo. Nada é enviado a lugar nenhum — você decide se e quando compartilhar.',
  settingsDiagnosticsSaveAction: 'Salvar arquivo',
  settingsDiagnosticsSavedTitle: 'Arquivo salvo',
  settingsDiagnosticsSavedBody: 'Arquivo de diagnóstico salvo em {path}.',
  settingsDiagnosticsNotSavedTitle: 'Nada foi salvo',
  settingsDiagnosticsReasonRateLimited: 'Você acabou de salvar um. Espere alguns segundos e tente de novo.',
  settingsDiagnosticsReasonWriteFailed: 'Não foi possível gravar o arquivo. Verifique o local de salvamento e tente de novo.',
  settingsDiagnosticsReasonNoSource: 'Ainda não há nada para salvar. O app ainda não se conectou ao jogo.',

  // settingsUpdates* — o controle de procurar/baixar/instalar atualizações
  settingsUpdatesSectionTitle: 'Atualizações',
  settingsUpdatesCurrentVersionLabel: 'Versão instalada',
  settingsUpdatesChannelHelp: 'Canal de atualização: {channel}.',
  settingsUpdatesCheckLabel: 'Procurar atualizações',
  settingsUpdatesCheckHelp:
    'Também procura sozinho pouco depois de o app abrir, e a cada vinte minutos enquanto ele ficar aberto.',
  settingsUpdatesCheckAction: 'Procurar agora',
  settingsUpdatesDownloadLabel: 'Uma versão nova está esperando',
  settingsUpdatesDownloadHelp: 'Baixar não interrompe nada — você instala quando quiser.',
  settingsUpdatesDownloadAction: 'Baixar',
  settingsUpdatesInstallLabel: 'Terminar a atualização',
  settingsUpdatesInstallHelp: 'Leva alguns segundos. O app abre de novo sozinho.',
  settingsUpdatesInstallAction: 'Reiniciar e instalar',
  settingsUpdatesStatusChecking: 'Procurando atualizações…',
  settingsUpdatesStatusUpToDate: 'Você está na versão mais recente.',
  settingsUpdatesStatusAvailableTitle: 'A versão {version} está disponível',
  settingsUpdatesStatusAvailableBody: 'Baixe agora, ou deixe para depois — o app pergunta de novo mais tarde.',
  settingsUpdatesStatusDownloading: 'Baixando a versão {version}… {percent}%',
  settingsUpdatesStatusReadyTitle: 'A versão {version} está pronta para instalar',
  settingsUpdatesStatusReadyBody: 'O app fecha e abre de novo na versão nova. Nada do que você salvou é perdido.',
  settingsUpdatesStatusDisabled:
    'As atualizações estão desligadas nesta versão. As versões Beta e estável instaladas se atualizam sozinhas; uma versão de desenvolvimento local não.',
  settingsUpdatesErrorTitle: 'Não foi possível procurar atualizações',
  settingsUpdatesReasonOffline:
    'Não foi possível acessar o servidor de atualizações. Verifique sua conexão e tente de novo.',
  settingsUpdatesReasonRateLimited:
    'O servidor de atualizações está pedindo para irmos mais devagar. Espere alguns minutos e tente de novo.',
  settingsUpdatesReasonNoRelease: 'Ainda não existe uma versão publicada para esta build.',
  settingsUpdatesReasonUnknown:
    'Algo deu errado. Tente de novo e, se continuar falhando, salve um arquivo para relatório de erro abaixo.',

  // settingsSupport* — a metade com rótulo do link de apoio; a barra superior tem a metade só com ícone
  settingsSupportSectionTitle: 'Apoie o projeto',
  settingsSupportCoffeeLabel: 'Me pague um café',
  settingsSupportCoffeeHelp: 'O companion é gratuito e continua gratuito. Abre a página no seu navegador.',
  settingsSupportCoffeeAction: 'Me pague um café',
  settingsSupportReferralLabel: 'Código de indicação',
  settingsSupportReferralHelp:
    'Cola na tela de convite do jogo. Cada conta usa um código de indicação só, e quando você passar da fase 151 a gente ganha uma recompensa.',

  // consentGate* — o portão de permissão mostrado no lugar do conteúdo do app quando o acesso não é permitido
  consentGateTitle: 'Este app precisa da sua permissão para funcionar',
  consentGateBody:
    'Desculpe — o companion não tem nada a mostrar sem acesso à sua conta. Ele lê sua conta e se conecta ao programa do jogo em execução, e não fará nenhuma das duas coisas até que você permita.',
  consentGateReadAgainAction: 'Ler o aviso novamente',
  consentGateLanguageLabel: 'Idioma',

  // error* — §2.8
  errorAccountReadFailedDescription: 'Tente novamente depois que o jogo terminar de carregar, ou reinicie o app.',

  // live* — a tela Ao Vivo: rótulo de navegação e a linha de status de atualização no topo do painel
  liveNavLabel: 'Ao vivo',

  // miniLive* — a segunda janela compacta do Ao Vivo: o botão que a abre na aba Ao vivo, o
  // próprio chrome dela e o menu de layout dos painéis. Chaves `*Aria` rotulam controles só de ícone.
  miniLiveOpenLabel: 'Abrir mini',
  miniLiveCloseAria: 'Fechar mini',
  miniLiveGearAria: 'Layout dos painéis',
  miniLiveAxisLabel: 'Direção de crescimento',
  miniLiveAxisVerticalLabel: 'Empilhado',
  miniLiveAxisHorizontalLabel: 'Em linha',
  miniLiveLastSectionNote: 'Pelo menos um painel precisa permanecer ligado',

  // windowControl* — os botões de janela do próprio cabeçalho, que são só de ícone, então cada
  // chave é o nome acessível do controle. Maximizar e restaurar são dois nomes para um botão:
  // qual deles vale depende de a janela já estar maximizada.
  windowControlMinimizeAria: 'Minimizar',
  windowControlMaximizeAria: 'Maximizar',
  windowControlRestoreAria: 'Restaurar tamanho',
  windowControlCloseAria: 'Fechar para a bandeja',

  liveStatusLiveLabel: 'Transmitindo ao vivo do jogo',
  liveStatusNotLiveLabel: 'Não ao vivo — mostrando o último estado conhecido',

  // liveGapReason* — uma causa para cada LiveGapReason (@bombfarm/contracts), mapeada de forma
  // exaustiva por LIVE_GAP_REASON_COPY_KEY abaixo.
  liveGapReasonClientNotStreaming:
    'O jogo está aberto, mas não está enviando nada no momento — pode estar em um menu, parado ou deslogado. O app continua tentando por conta própria.',
  liveGapReasonNeverAttached: 'O app ainda não se conectou ao jogo nesta sessão. Ele continua tentando por conta própria.',
  liveGapReasonAttachFailed: 'O app tentou se conectar ao jogo e não conseguiu. Ele continua tentando por conta própria.',
  liveGapReasonDetached: 'O app estava conectado, mas o jogo foi fechado. Ele continua tentando por conta própria.',
  liveGapReasonHookSilent:
    'A conexão ficou muda sozinha, mesmo com o jogo ainda aberto. O app continua tentando.',
  liveGapReasonRuntimeUnavailable: 'A parte do app que lê o jogo não conseguiu carregar. Ele continua tentando por conta própria.',
  liveGapReasonRuntimeUnavailableQuarantine:
    'Um antivírus provavelmente bloqueou a parte do app que lê o jogo. Ele continua tentando por conta própria.',
  liveGapReasonConsentMissing: 'Você ainda não permitiu que o app leia sua conta e se conecte ao jogo.',

  liveHeroesTitle: 'Heróis',
  liveListOnFieldTitle: 'Campo',
  liveListRecoveringTitle: 'Descansando',
  liveListQueuedTitle: 'Ociosos',
  liveListBenchedTitle: 'No banco',
  liveListEmptyLine: 'Nenhum herói aqui no momento.',
  liveEnergyLabel: 'Energia',
  liveEnergyRisingLabel: 'Subindo',
  liveEnergyFallingLabel: 'Caindo',
  liveFieldSlotsHint: 'Compre mais vagas de campo na sua árvore de habilidades',
  liveRestingSlotsHint: 'Ative uma casa superior para mais vagas de descanso',
  liveRestingCycleValue: 'Ciclo completo de descanso {duration}',
  liveRestingSkipsValue: '{left} de {max} resgates restantes hoje',
  liveRestingSkipsNone: 'Nenhum resgate restante hoje',
  liveUnclassifiedCount: 'Heróis não classificados em nenhuma lista: {n}',
  liveFieldExitPendingCount: 'Heróis que acabaram de sair do campo, ainda atualizando: {n}',

  // liveCountdown* — contagens de campo/descanso, e os qualificadores que marcam uma como estimada ou
  // pausada. Toda contagem usa uma única cor, então o qualificador é a única coisa que marca uma delas.
  liveFieldCountdownLabel: 'Tempo restante no campo',
  liveRecoveryCountdownLabel: 'Tempo restante de descanso',
  liveCountdownEstimatedQualifier: 'estimativa, não uma leitura direta',
  liveCountdownPausedQualifier: 'não está contando no momento',

  // liveNeverRead* — nada foi lido da conta ainda nesta sessão. O motivo de nada ter chegado vem
  // das strings liveGapReason* acima (esta tela reutiliza o texto em vez de repetir "abra o jogo"
  // enquanto o app já está funcionando); esta é a única descrição restante, para o caso em que a
  // transmissão já está ao vivo e só falta a leitura da conta.
  liveNeverReadTitle: 'Nada foi lido da sua conta ainda',
  liveNeverReadAccountPendingDescription: 'O app está conectado ao jogo e lendo sua conta agora.',

  // liveNeverReadFlavorLine* — texto de humor, mais discreto e rotativo, abaixo do sprite de
  // espera, mostrado só enquanto algo está realmente em andamento. Nunca promete um prazo (a
  // espera pode legitimamente durar um minuto) — é bem-humorado sobre a própria espera.
  liveNeverReadFlavorLine1: 'Contando o ouro, moeda por moeda.',
  liveNeverReadFlavorLine2: 'Dando um oi para os seus heróis.',
  liveNeverReadFlavorLine3: 'Esquentando o ábaco.',
  liveNeverReadFlavorLine4: 'Esperando com paciência. Bastante paciência.',
  liveNeverReadFlavorLine5: 'Dando uma cutucada amigável na planilha.',

  // liveEarnings* — o painel de Ganhos: valores medidos de ouro/XP, enviados já prontos e só
  // formatados aqui, nunca recalculados.
  liveEarningsTitle: 'Ganhos',
  liveEarningsResetAria: 'Reiniciar sessão',
  liveEarningsCurrentGoldLabel: 'Ouro atual',
  liveEarningsGoldHeadlineUnit: 'ouro / h',
  liveEarningsXpHeadlineUnit: 'xp / h',
  liveEarningsRecentWindowLabel: 'últimos {minutes} min',
  liveEarningsGoldSessionLabel: 'Ouro/h',
  liveEarningsXpSessionLabel: 'XP/h',
  liveEarningsGoldSessionTotalLabel: 'Total de ouro',
  liveEarningsXpSessionTotalLabel: 'Total de XP',
  liveEarningsElapsedLabel: 'Decorrido',
  liveEarningsXpHelpLabel: 'Sobre esse número de XP',
  liveEarningsXpHelpBody: 'Calculado a partir dos props que seus heróis destruíram, não lido diretamente do jogo.',
  liveEarningsSeriesLabel: 'Ouro / h — últimos {minutes} min',
  liveEarningsSeriesAria: 'Ouro por hora nos últimos {minutes} minutos',
  liveEarningsSeriesPeakLabel: 'pico {value}',
  liveEarningsMeasuredNote: 'Medido',
  liveEarningsMeasuredBody:
    'Medido a partir do que realmente caiu nos últimos 10 minutos — não estimado. Trocar de mapa mistura o que os dois pagaram até a janela se atualizar.',
  liveEarningsGoldPerPropLabel: 'Ouro / prop',
  liveEarningsPropsPerMinuteLabel: 'Props / min',
  liveEarningsPropsTotalLabel: 'Props',
  liveEarningsGoldPerPropUnder: '{percent}% abaixo da estimativa',
  liveEarningsGoldPerPropOver: '{percent}% acima da estimativa',
  liveEarningsGoldPerPropOnEstimate: 'na estimativa',

  // liveMap* — o painel de Mapa: em qual mapa se está jogando e o quanto da run já passou.
  liveMapTitle: 'Mapa',
  liveMapHealthLabel: 'Vida do mapa',
  liveMapPropsLabel: 'Props vivos',
  liveMapUnknownName: 'Mapa desconhecido',
  liveMapXpPerPropLabel: 'XP / prop',
  liveMapGoldPerPropLabel: 'Ouro / prop',
  liveMapGoldPerClearLabel: 'Ouro / limpeza',
  liveMapEstimateNote: 'Estimativa',
  liveMapEstimateBody:
    'Estimado a partir dos valores da wiki deste mapa e dos seus próprios bônus — a média que um prop ou uma limpeza completa paga, não o que você realmente ganhou.',

  // inventory* — a tela de Inventário: todos os itens da conta, agrupados por tipo
  inventoryNavLabel: 'Inventário',
  inventoryTitle: 'Inventário',
  inventoryGroupEquipment: 'Equipamentos',
  inventoryGroupGem: 'Gemas',
  inventoryGroupKey: 'Chaves',
  inventoryGroupOther: 'Outros',
  inventoryBadgeLocked: 'Bloqueado',
  inventoryBadgeMarketBlocked: 'Não pode ser negociado',
  inventoryBadgeUnresolved: 'Ainda não está na lista de itens',
  inventoryDetailSetSlot: '{set} · {slot}',
  inventoryDetailLevel: 'Nv {level}',
  inventoryEquippedByHero: '{hero} · Nível {level}',
  inventoryGroupTime: 'Peças de Casa',
  inventoryGroupStone: 'Pedras de habilidade',
  inventoryGroupChest: 'Baús',
  inventoryGemAmethyst: 'Ametista',
  inventoryGemAquamarine: 'Água-marinha',
  inventoryGemCitrine: 'Citrino',
  inventoryGemDiamond: 'Diamante',
  inventoryGemEmerald: 'Esmeralda',
  inventoryGemOceanite: 'Oceanita',
  inventoryGemRoselite: 'Roselita',
  inventoryGemRuby: 'Rubi',
  inventoryGemSapphire: 'Safira',
  inventoryGemTopaz: 'Topázio',
  inventoryChestItem: 'Baú de item · Nv {level}',
  inventoryChestGem: 'Baú de gemas',
  inventoryChestKey: 'Baú de chaves',
  inventoryChestSkill: 'Baú de pedras',
  inventoryChestTime: 'Baú de peças de Casa',
  inventoryChestHero: 'Jaula de herói · Ato {act}',
  inventorySearchPlaceholder: 'Buscar itens…',
  inventorySearchLabel: 'Buscar no inventário',
  inventoryFilterAll: 'Todos',
  inventoryFilterEquipped: 'Equipados',
  inventoryFilterPriced: 'Com preço',
  inventoryTotalsTitle: 'O que seu inventário poderia vender',
  inventoryTotalsCoverage: '{priced} de {tradable} itens negociáveis com preço',
  inventoryFilterClear: 'Limpar',
  inventoryFilterCount: '{shown} de {total}',
  inventoryFilterNoMatches: 'Nenhum item corresponde a esses filtros.',
  inventoryEquippedByUnknown: 'Equipado',
  inventoryFilterHeroLabel: 'Filtrar por herói',
  inventoryFilterAllHeroes: 'Todos os heróis',
  inventorySortLabel: 'Ordenar por',
  inventorySortRarity: 'Raridade',
  inventorySortLevel: 'Nível',
  inventorySortValue: 'Valor',
  inventorySortName: 'Nome',
  inventorySortCount: 'Quantidade',
  inventorySortMarket: 'Preço de mercado',
  inventoryViewLabel: 'Layout',
  inventoryViewCards: 'Cartões',
  inventoryViewList: 'Lista',
  inventoryTableCaption: 'Todos os itens da conta, em tabela ordenável',
  inventoryColumnEquippedBy: 'Equipado por',
  inventoryColumnForge: 'Forja',
  inventoryColumnActions: 'Ações',
  inventoryRowAction: 'Detalhes de {item}',
  marketNoListings: 'Sem anúncios',
  marketNotOnMarket: 'Fora do mercado',
  marketRefreshItem: 'Atualizar o preço de mercado de {item}',
  marketNativeTooltip: 'Menor anúncio na Steam, em {currency} — cotado {age}',
  marketConvertedTooltip: 'Aproximado: convertido do dólar, então a Steam pode mostrar outro valor — {age}',
  marketAgeJustNow: 'agora',
  marketAgeMinutes: 'há {count} min',
  marketAgeHours: 'há {count} h',
  marketAgeDays: 'há {count} d',
  marketAgeUnknown: 'em momento desconhecido',
  inventorySortAscending: 'Crescente',
  inventorySortDescending: 'Decrescente',
  inventoryFilterSetsLabel: 'Filtrar por set',
  inventoryFilterAllSets: 'Todos os sets',
  inventoryFilterSetsOwned: 'Sets que você tem',
  inventoryFilterSetsSelected: '{chosen} de {total} sets',
  inventoryFilterSelectAllSets: 'Selecionar todos',
  inventorySetOption: 'Nível {level} · {set}',
  inventoryUnknownCategory: 'um tipo que este app ainda não reconhece ({codes})',
  inventorySkipped: '{count} entradas não puderam ser lidas e não aparecem aqui.',
  inventoryEmptyTitle: 'Nenhum item lido ainda',
  inventoryEmptyDescription: 'Abra o jogo com o companion em execução, para que ele tenha o que ler.',

  // forge* — a tela da Forja: escolha uma peça, escolha um alvo, veja quanto a subida deve custar
  // e forje. Os níveis de forja chegam como valores (`{target}` é "+13"), nunca como
  // caracteres próprios.
  forgeNavLabel: 'Forja',
  forgeTitle: 'Forja',
  forgeSearchPlaceholder: 'Buscar equipamentos…',
  forgeSearchLabel: 'Buscar nos seus equipamentos',
  forgeSlotLabel: 'Filtrar por espaço',
  forgeAllSlots: 'Todos os espaços',
  forgeBandLabel: 'Filtrar por nível de forja',
  forgeBandAny: 'Qualquer forja',
  forgeBandOnly: 'Apenas {level}',
  forgeBandRange: 'De {from} a {to}',
  forgeBandFrom: '{level} ou mais',
  forgeHeroHint: 'Mostrando o que {hero} está usando',
  forgeTableCaption: 'Cada peça de equipamento da conta, ordenada pelo nível de forja',
  forgeRowSelect: 'Planejar uma subida para {item}',
  forgeItemTitle: 'Item',
  forgePickTitle: 'Escolha uma peça',
  forgePickDescription: 'Clique em uma linha para ver quanto uma subida deve custar.',
  forgeStatsCaption: 'Cada atributo da peça agora e no alvo',
  forgeColumnChange: 'Mudança',
  forgeStatsNote:
    'Todo atributo escala pelo mesmo fator — ×{factor} em {target} contra ×{now} agora — então isto é o que a peça vira se a subida der certo, não uma média de onde ela pode parar.',
  forgePlanTitle: 'Plano',
  forgeTargetLabel: 'Alvo',
  forgeTargetLower: 'Baixar o alvo',
  forgeTargetRaise: 'Subir o alvo',
  forgeSpanSafe: 'trecho seguro — todo passo acerta',
  forgeSpanRisky: 'trecho arriscado — {chance} no topo',
  forgeMaxGoldLabel: 'Ouro máximo',
  forgeMaxGoldPlaceholder: 'sem teto',
  forgeAttemptsLabel: 'Tentativas',
  forgeAttemptsPlaceholder: 'sem limite',
  forgeLadderCaption: 'Os degraus arriscados da subida e suas chances',
  forgeLadderFailTo: 'falha → {floor}',
  forgeFactRolls: 'Rolagens esperadas',
  forgeFactGold: 'Ouro esperado',
  forgeFactBadRun: 'Uma maré ruim (p90)',
  forgeFactWallet: 'Carteira',
  forgeWarnMax:
    '{max} é o único degrau que zera a peça para {floor}. Espere reconstruir a partir do piso seguro cerca de {times} vezes no caminho.',
  forgeWarnRisky:
    'Uma rolagem falha em {from}…{to} derruba a peça de volta para {floor}, e o ouro é cobrado de qualquer jeito.',
  forgeButton: 'Forjar até {target}',
  forgeReasonMaxed: 'Já está em {max} — não há mais o que forjar',
  forgeReasonFixture: 'Sem servidor para forjar',
  forgeReasonSwitchOff: 'Ligue "{switch}" em Configurações para forjar daqui',
  forgeReasonReady: 'Gasta ouro da sua conta — o botão pergunta duas vezes',
  forgeReasonRunning: 'Rolando — a execução para depois da rolagem em andamento',
  forgeReasonCancelling: 'Cancelando — esperando a rolagem em andamento terminar',
  forgeButtonConfirm: 'Confirmar — gasta ouro',
  forgeButtonCancel: 'Cancelar após esta rolagem',
  forgeButtonCancelPending: 'Cancelando após esta rolagem…',
  forgeStartBusy: 'Já há uma execução em andamento',
  forgeStartNotConsented: 'Aceite a leitura da conta em Configurações antes de forjar',
  forgeStartGameNotRunning: 'Abra o jogo antes de forjar',
  forgeStartTokenUnavailable: 'A sessão do jogo não pôde ser lida — abra o jogo e tente de novo',
  forgeStartUnknownItem: 'Esta peça não está mais na conta — atualize a mochila',
  forgeStartBadTarget: 'O alvo ficou atrás da peça — atualize a mochila',
  forgeStartUnavailable: 'O app ainda está iniciando — tente de novo em instantes',
  accountReadRecent: 'Acabou de ler agora há pouco — a conta já está no ponto',
  accountReadFixture: 'Sem servidor para ler',
  accountReadNotConsented: 'Aceite a leitura da conta em Configurações para atualizar',
  accountReadGameNotRunning: 'Abra o jogo para ler a conta de novo',
  forgeLedgerTitle: 'Registro de execuções',
  forgeLedgerSummary: '{runs} execuções',
  forgeLedgerGold: '{spent} de ouro',
  forgeLedgerCaption: 'Todas as forjas que este app fez na conta, da mais recente para a mais antiga',
  forgeLedgerEmptyTitle: 'Nenhuma execução ainda',
  forgeLedgerEmptyDescription: 'Uma execução iniciada pelo painel do plano fica guardada aqui.',
  forgeLedgerColumnWhen: 'Quando',
  forgeLedgerColumnItem: 'Peça',
  forgeLedgerColumnClimb: 'Subida',
  forgeLedgerColumnOutcome: 'Desfecho',
  forgeLedgerColumnRolls: 'Rolagens',
  forgeLedgerColumnFails: 'Falhas',
  forgeLedgerColumnCrits: 'Críticos',
  forgeLedgerColumnSafeJumps: 'Saltos seguros',
  forgeLedgerColumnGold: 'Ouro',
  forgeLedgerColumnDuration: 'Duração',
  forgeLedgerTotals: '{runs} execuções · {rolls} rolagens · {fails} falhas',
  forgeLedgerClear: 'Limpar o registro',
  forgeLedgerClearTitle: 'Limpar o registro da forja?',
  forgeLedgerClearDescription: 'Todas as execuções passadas e os totais vão junto. O ouro foi gasto de qualquer forma.',
  forgeLedgerClearConfirm: 'Limpar',
  forgeLedgerClearCancel: 'Manter',
  forgeStopTarget: 'Chegou',
  forgeStopCancelled: 'Cancelada',
  forgeStopShortfall: 'Ouro acabou',
  forgeStopBudget: 'Orçamento de ouro',
  forgeStopAttempts: 'Limite de tentativas',
  forgeStopCooldown: 'Servidor em espera',
  forgeStopMissing: 'Item recusado',
  forgeStopError: 'Erro',
  forgeRailRolls: '{rolls} rolagens',
  forgeRailSpent: '{spent} de ouro',
  forgeRailWallet: 'carteira {wallet}',
  forgeRailTallyCaption: 'Rolagens por degrau',
  forgeRailTallyRung: 'Degrau',
  forgeRailTallyRolls: 'Rolagens',
  forgeRailTallyFails: 'Falhas',
  forgeRailTallyGold: 'Ouro',
  forgeChartLabel: 'A subida, um ponto por chamada',
  forgeChartFloor: 'piso',
  forgeChartTarget: 'alvo',
  forgeMarkSuccess: 'acertou',
  forgeMarkCritical: 'crítico',
  forgeMarkFail: 'errou',
  forgeMarkSafe: 'salto seguro',
  forgeMarkPending: 'rolando',
  forgeResultReached: 'Chegou a {level}',
  forgeResultCancelled: 'Parou em {level} — cancelada após a rolagem {rolls}',
  forgeResultShortfall: 'Ouro acabou em {level}',
  forgeResultBudget: 'Parada pelo orçamento de ouro em {level}',
  forgeResultAttempts: 'Parada pelo limite de tentativas em {level}',
  forgeResultCooldown: 'Servidor em espera em {level}',
  forgeResultMissing: 'O servidor recusou o item',
  forgeResultError: 'Parada por um erro em {level}',
  forgeResultClimb: 'Subida',
  forgeResultRolls: 'Rolagens · falhas · críticos',
  forgeResultSpent: 'Gasto',
  forgeResultDuration: 'Duração',
  forgeAgainstPlanTitle: 'Contra o plano',
  forgeAgainstExpected: 'esperado',
  forgeAgainstBadRun: 'uma má sequência',
  forgeAgainstUnder: 'abaixo do que o plano esperava',
  forgeAgainstOver: 'acima do que o plano esperava',
  forgeAgainstWorse: 'pior que uma má sequência',
  forgeAgainstExact: 'exatamente o que o plano esperava',
  forgeAgainstNoPlan: 'Sem plano para comparar — esta execução não partiu do painel',
  forgeDone: 'Concluir',
  forgeQueueAdd: 'Pôr na fila',
  forgeQueueAdded: 'Na fila',
  forgeQueueAddAria: 'Pôr {item} na fila de forja, até {target}',
  forgeQueueAddedAria: '{item} está na fila de forja, até {target}',
  forgeQueueTitle: 'Fila de forja',
  forgeQueueOpenForge: 'Fila de forja — abrir a aba Forja',
  forgeQueueForged: '{done}/{total} forjadas',
  forgeQueueRolling: 'rolando',
  forgeQueueProgress: '{rolls} rolagens · {spent} ouro',
  forgeQueueStopped: 'Parou — {reason}',
  forgeQueueStart: 'Iniciar',
  forgeQueueResume: 'Retomar',
  forgeQueueCancel: 'Cancelar',
  forgeQueueRemove: 'Tirar {item} da fila',
  forgeQueueClear: 'Limpar',
  forgeQueueClearAria: 'Limpar a fila de forja',
  forgeQueueConfirmTitle: 'Iniciar a fila de forja?',
  forgeQueueConfirmOne: 'Forja {item} até {target} e gasta ouro da sua conta — cerca de {gold} esperado.',
  forgeQueueConfirmMany:
    'Forja {count} peças em sequência e gasta ouro da sua conta — cerca de {gold} esperado. A fila para se uma peça parar antes do alvo.',
  forgeQueueConfirmNoEstimate: 'Gasta ouro da sua conta; sem estimativa para estas peças. A fila para se uma peça parar antes do alvo.',
  forgeQueueConfirm: 'Iniciar — gasta ouro',
  forgeQueueConfirmCancel: 'Agora não',
  forgeQueuePanelCaption: 'Forjadas em sequência, de cima para baixo; uma peça que já chegou ao alvo sai sozinha.',

  accountNavLabel: 'Conta',
  accountPanelTitle: 'Sua conta',
  accountReadAge: 'Conta lida {age}',
  accountUnavailableTitle: 'Sua conta ainda não foi lida',
  accountUnavailableDescription: 'Abra o jogo com o companion em execução e deixe aberto por um instante.',

  accountIdentityTip: 'De quem é esta conta e até onde ela chegou, lido do jogo enquanto ele roda.',
  accountPlayerName: 'Jogador',
  accountIdLabel: 'ID da conta',
  accountCurrentPhase: 'Fase atual',
  accountMaxPhase: 'Fase mais distante',

  accountHouse: 'Casa',
  accountHouseLevel: 'Nível da casa',
  accountHouseTip: 'Sua Casa define quanto tempo um herói descansa entre as idas ao campo, e quantos descansam ao mesmo tempo. A próxima Casa aparece no nível 1 dela, que é o que você recebe assim que desbloqueá-la.',
  accountHouseTipMaxed: 'Sua Casa define quanto tempo um herói descansa entre as idas ao campo, e quantos descansam ao mesmo tempo. A Casa V é a última — não há nada acima dela.',
  accountHouseCycle: 'Ciclo de descanso',
  accountHouseCycleTip: 'Um herói indo de vazio a cheio. Vem do jogo quando ele informa um valor para esta Casa e nível exatos; caso contrário, sai dos valores de nível 1 e nível 20 da própria Casa.',
  accountHouseSlots: 'Vagas de descanso',
  accountHouseSlotsTip: 'Quantos heróis a Casa recupera ao mesmo tempo. Heróis além disso esperam com energia congelada até vagar um espaço.',
  accountNextHouse: 'Próxima Casa — {house}',

  accountTreePanelTitle: 'Árvore de habilidades',
  accountTreeTip: 'Todos os bônus da conta que sua árvore de habilidades concede, como o jogo os soma.',
  accountTreeGroupDamage: 'Dano',
  accountTreeGroupField: 'Campo',
  accountTreeGroupRewards: 'Recompensas',
  accountSquadDamage: 'Dano do esquadrão',
  accountGeoMultiplier: 'Dano multiplicativo',
  accountTotalDamage: 'Dano total',
  accountTotalDamageTip: 'O dano total é a multiplicação dos dois acima, não um terceiro bônus à parte: um dano de esquadrão de {squad}% com multiplicador de {geo} chega a {total}. Todo número de dano deste app já inclui isso, então nunca some dano do esquadrão ou multiplicativo de novo.',
  accountCritChance: 'Chance de crítico',
  accountCritDamage: 'Dano crítico',
  accountSpeed: 'Velocidade',
  accountEnergy: 'Energia máxima',
  accountFieldSlots: 'Vagas no campo',
  accountFieldSlotsTip: 'O resumo do próprio jogo mostra o que a árvore adiciona; o total, contando a vaga que toda conta já tem, é o que realmente limita seu campo.',
  accountBonusOfTotal: '{bonus} ({total} no total)',
  accountGold: 'Ouro por alvo',
  accountGoldTip: 'O bônus de ouro da árvore de habilidades — escala o ouro que cada prop paga.',
  accountLuck: 'Sorte',
  accountXp: 'Experiência do herói',
  accountBagTabs: 'Abas da bolsa',

  accountHoldingsTotal: 'O que esta conta poderia vender',
  accountHoldingsPartial: 'apenas parte da conta',
  accountHoldingsCoverage: '{priced} de {eligible} coisas vendáveis com preço agora',
  accountHoldingsMissing: 'Fora desta conta: {rows}.',
  accountHoldingsPricesOldest: 'preço mais antigo {age}',
  accountHoldingsUnpriced: 'sem oferta',
  accountHoldingsInventory: 'Inventário',
  accountHoldingsInventoryCoverage: '{priced} de {eligible} itens negociáveis com preço',
  accountHoldingsInventoryWithheld: 'Seu inventário ainda não foi lido',
  accountHoldingsInventoryLink: 'Abrir o inventário',
  accountHoldingsHeroes: 'Heróis',
  accountHoldingsHeroesCoverage: '{priced} de {eligible} heróis vendáveis com preço',
  accountHoldingsHeroesWithheld: 'Seus heróis ainda não foram lidos',
  accountHoldingsHeroesFloor: 'Uma oferta de herói é precificada só pela raridade — nível, equipamento e habilidades não valem nada nela — então este é um piso, nunca o que um herói bem construído alcança.',
  accountHoldingsSkins: 'Skins em uso',
  accountHoldingsSkinsCoverage: '{priced} de {eligible} skins compradas com preço',
  accountHoldingsSkinsWithheld: 'Seus heróis ainda não foram lidos',
  accountHoldingsSkinsWorn: 'Uma skin comprada conta uma vez, por mais heróis que a usem, e só enquanto algum deles ainda a usa — devolva todos à skin de nascimento e este valor cai sem nada ter sido vendido.',

  farmNavLabel: 'Farm',
  farmRefresh: 'Atualizar',
  farmRefreshedAge: 'conta lida {age}',
  farmRefreshStale: 'desatualizado',
  farmUnavailableTitle: 'Ainda falta ler parte da sua conta',
  farmUnavailableDescription: 'O quadro precisa de todas as partes da sua conta. Abra o jogo com o companion em execução e deixe aberto por um instante.',
  farmLeftOutTitle: 'Alguns heróis ficaram fora do quadro',
  farmLeftOutBody: 'O app não conseguiu ler os pontos de atributo gastos de {heroes} na conta, então as taxas deles não podem ser calculadas e eles ficam fora deste quadro.',
  farmStatColumn: 'Atributo',
  farmStatLuck: 'Sorte',

  heroesNavLabel: 'Heróis',
  heroesNeverReadTitle: 'Nada foi lido da sua conta ainda',
  heroesNeverReadDescription: 'Abra o jogo com o companion em execução, e seus heróis aparecerão aqui.',
  heroesNoneTitle: 'Esta conta não tem heróis',
  heroesNoneDescription: 'Sua conta foi lida e ainda não há ninguém para mostrar aqui.',
  heroesViewLabel: 'Layout',
  heroesSortLabel: 'Ordenar por',
  heroesSortRoll: 'Sorteio',
  heroesSortPower: 'Poder',
  heroesSortLevel: 'Nível',
  heroesSortRarity: 'Raridade',
  heroesSortRank: 'Nota',
  heroesSortStars: 'Estrelas',
  heroesSortAscending: 'Pior primeiro',
  heroesSortDescending: 'Melhor primeiro',
  heroesFilterActiveHeroes: 'Heróis ativos',
  heroesAbilityFilterLabel: 'Filtrar por habilidade',
  heroesAbilityFilterOption: 'Só heróis com {ability}',
  heroesAbilityFilterAbsent: 'Nenhum herói aqui tem {ability}',
  heroesViewCards: 'Cartões',
  heroesViewList: 'Lista',
  heroesDensityLabel: 'Detalhe do cartão',
  heroesDensityCompact: 'Compacto',
  heroesDensityCombat: 'Combate',
  heroesDensityFull: 'Completo',
  heroesCardSheetStatsLabel: 'Atributos',
  heroesCardBirthStatsLabel: 'Stats de nascimento',
  heroesTabHero: 'Herói',
  heroesTabCombat: 'Combate',
  heroesTabGear: 'Equipamento',
  heroesTabPoints: 'Pontos',
  heroesRosterTitle: 'Seu elenco',
  heroesRosterListLabel: 'Seus heróis',
  heroesFiguresWithheldTitle: 'Ainda não foi lido o bastante da sua conta',
  heroesFiguresWithheldDescription: 'Os números de cada herói precisam da sua árvore de habilidades e da sua Casa. Deixe o jogo aberto por um instante e eles vão aparecer.',
  heroesPointsUnreadTitle: 'Os pontos de atributo gastos deste herói não puderam ser lidos',
  heroesPointsUnreadDescription: 'A ficha que o jogo informou para este herói não fecha com o modelo atual, então os pontos, os números de equipamento e os de combate ficam retidos em vez de desenhados como se ele não tivesse gasto nenhum.',
  heroesPhaseUnknownTitle: 'Esta não é uma fase que o app conhece',
  heroesPhaseUnknownDescription: 'Escolha uma fase que o jogo tenha de verdade, e os números voltam.',

  optimizerNavLabel: 'Otimizador',
  optimizerUnavailableDescription: 'O otimizador precisa de todas as partes da sua conta. Abra o jogo com o companion em execução e deixe aberto por um instante.',
  optimizerEmptyNoRosterTitle: 'Nenhum herói nesta conta',
  optimizerEmptyNoRosterBody: 'Sua conta foi lida e não tem heróis, então ainda não há o que planejar.',
  optimizerEmptyNoInventoryTitle: 'Nenhum equipamento nesta conta',
  optimizerEmptyNoInventoryBody: 'Sua conta foi lida e não tem equipamentos, então ainda não há o que mover ou forjar.',
  optimizerEmptyAllLeaveAloneTitle: 'Nada no escopo',
  optimizerEmptyAllLeaveAloneBody: 'Marque pelo menos um herói como Otimizar antes de rodar um plano.',
  optimizerBlockedBody: 'A leitura da conta não trouxe o que a busca precisa de {heroes}, então ela não consegue pontuá-los.',
  optimizerFarmNeedsMaxPhase: 'Deixar a busca escolher a própria fase exige a fase mais distante que sua conta alcançou, que esta leitura não trouxe. Escolha uma fase acima, ou pontue por dano.',
  optimizerLeftOutTitle: 'Alguns heróis ficaram fora da busca',
  optimizerLeftOutBody: 'O app não conseguiu ler os pontos de atributo gastos de {heroes} na leitura da conta, então eles ficaram fora desta busca: não estão no quadro de escopo nem no plano.',

  pvpNavLabel: 'PVP',
  pvpStandingTitle: 'Sua posição',
  pvpStandingTier: 'Faixa',
  pvpStandingTierNote: 'A próxima faixa começa em {next} pontos.',
  pvpStandingPoints: 'Pontos',
  pvpStandingPointsValue: '{points} / {next}',
  pvpStandingDuels: 'Duelos restantes hoje',
  pvpStandingDuelsValue: '{left} de {max}',
  pvpStandingSlots: 'Vagas no esquadrão',
  pvpStandingSlotsValue: '{slots} de {max}',
  pvpStandingRank: 'Ranking',
  pvpStandingRankValue: '#{position}',
  pvpStandingRankNote: 'Sua posição no ranking de pontos, lida {age} com {points} pontos.',
  pvpStandingRankUnknown: 'Ainda não lido',
  pvpStandingUnknown: 'Ainda não lido',
  pvpStandingAge: 'lido {age}',
  pvpStandingEmpty: 'Nada lido ainda — sua posição é pedida quando esta aba abre, com o jogo aberto.',
  pvpFilterOpponentLabel: 'Oponente',
  pvpFilterOpponentAll: 'Todos os oponentes',
  pvpFilterOpponentSearch: 'Digite um nome',
  pvpFilterOpponentNoMatch: 'Nenhum oponente com esse nome',
  pvpFilterResultLabel: 'Resultado',
  pvpFilterResultAll: 'Todos',
  pvpFilterEmpty: 'Nenhum duelo corresponde a esses filtros.',
  pvpHeadToHeadTitle: 'Contra {name}',
  pvpHeadToHeadDuels: 'Duelos',
  pvpHeadToHeadWon: 'Vitórias',
  pvpHeadToHeadLost: 'Derrotas',
  // pvpStanding* additions (standing panel).
  pvpStandingMeterLabel: 'Faixa {tier} para a faixa {next}',
  pvpStandingEta: 'Faltam {wins}, a {step} por vitória',
  pvpStandingEtaWithDays: 'Faltam {wins}, a {step} por vitória — cerca de {days} na cota de hoje',
  pvpStandingEtaWins: '{wins} vitórias',
  pvpStandingEtaDays: '{days} dias',
  pvpStandingTrendLabel: 'Pontos após cada duelo',
  pvpStandingTrendSummary: 'últimos {n}, {pct}% de vitórias, sequência {streak}',
  pvpStandingTrendAria: 'Pontos após cada um dos últimos {n} duelos',
  pvpStandingStreakWon: 'V{n}',
  pvpStandingStreakLost: 'D{n}',
  pvpStandingTrendEmpty: 'A tendência de pontos precisa de pelo menos dois duelos.',
  pvpStandingLegendWon: 'vitória',
  pvpStandingLegendLost: 'derrota',
  pvpRivalsTitle: 'Rivais',
  pvpRivalsNote: 'Seu retrospecto por oponente — um clique define o filtro.',
  pvpRivalsFew: 'Os rivais aparecem depois de dois oponentes diferentes enfrentados.',
  pvpRivalsColumnRecord: 'Retrospecto',
  pvpRivalsColumnLast: 'Último',
  pvpRivalsRecord: '{won}–{lost}',
  pvpRivalsRecordHint: 'Duelos vencidos, depois duelos perdidos, contra este oponente.',
  pvpRivalsMarginHint: 'Seu placar somado sobre o deles, em todos os duelos contra este oponente.',
  pvpRivalsLastWon: 'vitória {age}',
  pvpRivalsLastLost: 'derrota {age}',
  pvpSquadColumn: 'Seu esquadrão',
  pvpSquadHint: 'Os heróis que você escalou, na ordem das vagas. Uma vaga com interrogação é um herói que já não está no seu elenco.',
  pvpSquadUnknownHero: 'Herói fora do elenco',
  pvpSquadUnknownMark: '?',
  pvpReplayTitle: 'Replay do duelo',
  pvpReplayNote: '{opponent}, filme {id}, {frames} quadros a {hz} Hz',
  pvpReplayClose: 'Fechar',
  pvpReplayLoading: 'Lendo o filme…',
  pvpReplayMissing: 'Este filme não está guardado.',
  pvpReplayLeadTaken: 'Virada',
  pvpReplayLeadTakenAt: 'aos {s} s',
  pvpReplayLeadTakenNever: 'nenhuma',
  pvpReplayWidestLead: 'Maior vantagem',
  pvpReplayWidestLeadAt: 'aos {s} s',
  pvpReplayRoomHp: 'HP da sala restante',
  pvpReplayBombs: 'Bombas',
  pvpReplayBombsValue: '{a} contra {d}',
  pvpReplayChartLabel: 'Dano por segundo: o seu, o deles e o HP da sala restante',
  pvpReplayAxisSeconds: '{s} s',
  pvpReplayLegendYou: 'você {total}',
  pvpReplayLegendOpponent: '{opponent} {total}',
  pvpReplayLegendRoomHp: 'HP da sala {pct}',
  pvpReplayLegendAt: 'aos {s} s',
  pvpHeadToHeadScore: 'Placar',
  pvpTitle: 'Histórico de duelos',
  pvpSummary: '{duels} duelos · {won} vitórias · {films} filmes guardados',
  pvpCaption: 'Todo duelo que este app viu terminar, do mais recente ao mais antigo',
  pvpEmptyTitle: 'Nenhum duelo ainda',
  pvpEmptyDescription: 'Lute um duelo com este app aberto e ele fica guardado aqui, com o filme.',
  pvpColumnWhen: 'Quando',
  pvpColumnOpponent: 'Oponente',
  pvpColumnResult: 'Resultado',
  pvpColumnScore: 'Placar',
  pvpColumnPhase: 'Fase da sala',
  pvpColumnPoints: 'Pontos',
  pvpColumnFilm: 'Filme',
  pvpOpponentHeroes: '{n} heróis',
  pvpResultWon: 'Vitória',
  pvpResultLost: 'Derrota',
  pvpScore: '{yours} contra {theirs}',
  pvpScoreHint: 'Seu placar primeiro, depois o deles: o HP que cada lado arrancou do outro ao longo do duelo.',
  pvpPhaseCell: '{phase} (F{tier}, piso {floor})',
  pvpPhaseHint: 'A fase em que o duelo foi lutado, depois sua faixa e a fase mais baixa em que essa faixa luta.',
  pvpPoints: '{before} → {after}',
  pvpFilmStored: 'Guardado',
  pvpFilmMissing: 'Não guardado',
  pvpFilmReplay: 'Ver replay',
  pvpFilmNote: 'Um filme é guardado no momento em que o jogo o busca. O servidor descarta o filme segundos depois, então um que foi pulado ou perdido não pode ser buscado agora.',

  skillsNavLabel: 'Árvore',
  skillsTitle: 'Árvore de habilidades',
  skillsTip: 'Cada nó da sua árvore como o jogo desenha, e quanto o próximo nível de cada um vale para o seu farm.',
  skillsUnreadableTitle: 'Sua árvore de habilidades ainda não foi lida',
  skillsArmHub: 'Hub',
  skillsArmDano: 'Dano',
  skillsArmCrit: 'Crítico',
  skillsArmVelocidade: 'Velocidade',
  skillsArmOuro: 'Ouro',
  skillsArmDrop: 'Drop/Sorte',
  skillsArmEnergia: 'Energia',
  skillsArmGeo: 'Geométrico',
  skillsArmNeutro: 'Eixo Neutro',
  skillsTierStart: 'Início',
  skillsTierSmall: 'Pequeno',
  skillsTierNotavel: 'Notável',
  skillsTierUnlock: 'Desbloqueio',
  skillsKindTeamDmg: 'Dano do Esquadrão',
  skillsKindCritChance: 'Chance Crítica',
  skillsKindCritDmg: 'Dano Crítico',
  skillsKindSpeed: 'Velocidade',
  skillsKindCoin: 'Ouro por Alvo',
  skillsKindLuck: 'Sorte',
  skillsKindEnergia: 'Energia do Herói',
  skillsKindXp: 'XP do Esquadrão',
  skillsKindGeo: 'Dano Composto',
  skillsKindFieldSlot: 'Vaga de Campo',
  skillsKindBagTab: 'Aba de Bolsa',
  skillsEffectTeamDmg: '{v} dano do esquadrão',
  skillsEffectCritChance: '{v} chance de crítico',
  skillsEffectCritDmg: '{v} dano crítico',
  skillsEffectSpeed: '{v} velocidade',
  skillsEffectCoin: '{v} ouro por alvo',
  skillsEffectLuck: '{v} sorte (baú)',
  skillsEffectEnergia: '{v} energia máx',
  skillsEffectXp: '{v} XP de herói',
  skillsEffectGeo: '{v} GEO (multiplicativo)',
  skillsEffectFieldSlot: '{n} herói em campo',
  skillsEffectBagTab: '{n} aba de bolsa',
  skillsLevel: 'Nível {level}/{max}',
  skillsHubName: 'Reator de Detonação',
  skillsHubNote: 'O coração da árvore — aceso desde o início, 5% a mais de dano do esquadrão.',
  skillsStateOwned: 'Comprado',
  skillsStateMaxed: 'No máximo',
  skillsStateBuyable: 'Pode comprar',
  skillsStateUnaffordable: 'Ouro insuficiente',
  skillsStateLockedPrerequisite: 'Precisa de {parent} no nível {need} — você tem {have}',
  skillsStateLockedPhase: 'Desbloqueia após a fase {phase}',
  skillsAlwaysLit: 'Aceso desde o início',
  skillsNextLevelCost: 'Próximo nível',
  skillsCostToMax: 'Até o máximo',
  skillsRefund: 'Reembolso',
  skillsRefundTip: 'Desfazer um nível devolve metade do que aquele nível custou, um nível por vez, das pontas para o centro.',
  skillsRefundBlocked: 'Não dá para desfazer enquanto {children} ainda depende dele',
  skillsWallet: 'Ouro em mãos',
  skillsGoldAmount: '{gold} de ouro',
  skillsNextToBuy: 'Próxima compra',
  skillsNextToBuyTip: 'Cada nó que você pode comprar agora, ordenado pelo que um nível a mais rende por milhão de ouro.',
  skillsObjectiveGold: 'Ouro/h',
  skillsObjectiveGate: 'Portão',
  skillsObjectivePvp: 'PVP',
  skillsColNode: 'Nó',
  skillsColCost: 'Custo',
  skillsColGain: 'Ganho médio',
  skillsColPerMillion: 'Por 1M',
  skillsGainDps: '{v} DPS',
  skillsPerMillionGold: '{v}',
  skillsPerMillionDps: '{v} DPS',
  skillsGainOutsideObjectives: 'Rende em drops, XP ou espaço na bolsa — não em ouro por hora nem em DPS',
  skillsNothingToRecommend: 'Nada para ordenar: nenhum nó pode ser comprado agora.',
  skillsPvpEmpty: 'O esquadrão de PVP está vazio. A ordenação espera os heróis nos slots em vez de inventar um time.',
  skillsPricingUnavailable: 'O elenco não pôde ser precificado, então nenhum nó tem valor ainda. A árvore continua visível.',
  skillsPricedAtPhase: 'Precificado na fase {phase}, a que sua aba Farm está usando.',
  skillsPricedAtAccountPhase: 'Precificado na fase {phase}, a que sua conta está farmando agora — escolha uma fase na aba Farm para precificar em outra.',
  skillsPricedAtGate: 'Clear cronometrado do portão da fase {phase} ({secs}s).',
  skillsPricedAtPvp: 'Janela de {secs}s no PVP, na fase {phase}.',
  skillsGatePhaseSelect: 'Fase do portão',
  skillsGatePhaseSearchPlaceholder: 'Difícil, Normal 2-1 ou 150',
  skillsGatePhaseNoMatch: 'Nenhum portão corresponde a isso.',
  skillsGatePhaseMoreMatches: 'Mostrando {shown} de {matched} — continue digitando para afunilar.',
  skillsNodeTitleC07: 'Golpe Preciso',
  skillsNodeTitleC12: 'Olho Mortal',
  skillsNodeTitleD07: 'Fúria Explosiva',
  skillsNodeTitleD12: 'Devastação',
  skillsNodeTitleE07: 'Fôlego Profundo',
  skillsNodeTitleE11: 'Coração da Mina',
  skillsNodeTitleN01: 'Vaga de Campo I',
  skillsNodeTitleN03: 'Vaga de Campo II',
  skillsNodeTitleN05: 'Vaga de Campo III',
  skillsNodeTitleN07: 'Vaga de Campo IV',
  skillsNodeTitleN09: 'Vaga de Campo V',
  skillsNodeTitleN11: 'Vaga de Campo VI',
  skillsNodeTitleN13: 'Vaga de Campo VII',
  skillsNodeTitleN15: 'Vaga de Campo VIII',
  skillsNodeTitleO08: 'Veio de Ouro',
  skillsNodeTitleO12: 'Febre do Ouro',
  skillsNodeTitleP01: 'Gume Cruel',
  skillsNodeTitleP02: 'Reflexo Afiado',
  skillsNodeTitleP03: 'Passo Lucrativo',
  skillsNodeTitleP04: 'Mão Cheia',
  skillsNodeTitleP05: 'Brisa da Fortuna',
  skillsNodeTitleP06: 'Pulso Constante',
  skillsNodeTitleP07: 'Pressão Tectônica',
  skillsNodeTitleS02: 'Aba de Inventário',
  skillsNodeTitleS05: 'Aba de Inventário',
  skillsNodeTitleS07: 'Achado Raro',
  skillsNodeTitleS11: 'Tesouro Oculto',
  skillsNodeTitleT01: 'Sangue & Ouro',
  skillsNodeTitleT02: 'Tempestade Precisa',
  skillsNodeTitleT03: 'Fortuna Dobrada',
  skillsNodeTitleT04: 'Pulso da Terra',
  skillsNodeTitleT05: 'Caçador de Relíquias',
  skillsNodeTitleT06: 'Geometria Dourada',
  skillsNodeTitleV08: 'Ímpeto',
  skillsNodeTitleV13: 'Vendaval',
  skillsDpsLeftOut: 'Fora do valor de DPS — sem atributos de nascimento registrados: {names}',
  skillsAffordableNow: 'Dá para comprar agora',
  skillsCloseNode: 'Fechar este nó',
  skillsPreview: 'Um nível acima',
  skillsPreviewTip: 'Seu farm recalculado com este nó um nível acima, contra a árvore como está. O ouro por hora é a média nas vizinhanças do elenco, para que um degrau de golpes até matar não vire cara ou coroa.',
  skillsPreviewGold: 'Ouro por hora',
  skillsPreviewGate: 'DPS no portão {phase}',
  skillsPreviewPvp: 'DPS no duelo, fase {phase}',
  skillsTotalNowNext: '{now} → {next}',
  skillsRequires: 'Requer',
  skillsGate: 'Portão de fase',
  skillsArm: 'Braço',
  skillsTier: 'Camada',
  skillsEffects: 'Efeitos',
  skillsTotals: 'Totais da árvore',
  skillsTotalsTip: 'O que a árvore inteira concede hoje, como o jogo soma.',
  skillsTotalTeamDmg: 'Dano do squad',
  skillsTotalCritChance: 'Chance de crítico',
  skillsTotalCritDmg: 'Dano crítico',
  skillsTotalSpeed: 'Velocidade',
  skillsTotalCoin: 'Ouro por alvo',
  skillsTotalLuck: 'Sorte',
  skillsTotalEnergia: 'Energia máx',
  skillsTotalDmgStatic: 'Dano total (estático)',
  skillsTotalGeo: 'Dano multiplicativo',
  skillsTotalXp: 'XP de herói',
  skillsTotalFieldSlots: 'Vagas de campo',
  skillsTotalBagTabs: 'Abas de bolsa',
  skillsLevelsBought: 'Níveis comprados',
  skillsCountOf: '{part} / {whole}',
  skillsGoldSpent: 'Ouro gasto',
  skillsGoldToMax: 'Ouro para completar a árvore',
  skillsPaths: 'Progresso por caminho',
  skillsNodesMaxed: '{maxed} de {nodes} nós no máximo',
  skillsFitToView: 'Ajustar à tela',
  skillsZoomIn: 'Aproximar',
  skillsZoomOut: 'Afastar',
  skillsLegend: 'Legenda',
  skillsLegendOwned: 'Comprado',
  skillsLegendBuyable: 'Pode comprar',
  skillsLegendUnaffordable: 'Falta ouro',
  skillsLegendLocked: 'Bloqueado',
  skillsLegendRecommended: 'Melhor valor',
  skillsLegendPathNote: 'A cor do anel é o caminho; a espessura e o brilho são o estado. Falta ouro fica vermelho em todo caminho.',
  skillsCanvasAria: 'Mapa da árvore de habilidades',
  skillsNodeAria: '{name}, nível {level} de {max}',
  // *AurasAtCap* — as fichas de aura no Farm e no Otimizador; ver o comentário em `en.ts`.
  farmAurasAtCapLabel: 'Auras com 100% de uptime',
  farmAurasAtCapHint: 'Cada aura acesa é calculada como se mantivesse o campo inteiro no teto 100% do tempo, seja o que for que o seu rodízio sustentaria sozinho. Apagada, a aura conta pela fração do tempo em que seus portadores estão em campo.',
  optimizerAurasAtCapLabel: 'Auras com 100% de uptime',
  optimizerAurasAtCapHint: 'Cada aura acesa é pontuada como se mantivesse o campo inteiro no teto 100% do tempo, seja o que for que o elenco sustentaria sozinho. Apagada, a aura conta pela fração do tempo em que seus portadores estão em campo.',

  heroAvatarCol: 'Avatar',
  heroBattleActive: 'Ativado',
  heroBattleActiveTitle: 'Ativado no rodízio',
  heroBattleInactive: 'Desativado',
  heroBattleInactiveTitle: 'Desativado no rodízio',
  heroBattleToggleAria: 'Ativar ou desativar este herói no rodízio',
  heroRank: 'Rank',
  heroStripSwitch: 'Trocar herói',
  gearSlotEmptyAria: '{slot} — vazio',
  gearSlotEmptyTip: 'Vazio',
  importClose: 'Fechar',
  importColLevel: 'Nv',
  importColName: 'Nome',
  importColPower: 'Poder',
  importColRank: 'Rank',
  importColRarity: 'Raridade',
  modeDps: 'DPS',
  rankLv: 'Nv',
  rosterColAbilities: 'Habilidades',
  rosterColGear: 'Equip.',
  rosterColStatus: 'Status',
  switchHero: 'Trocar herói',
  switchHeroDesc: 'Escolha entre {n} heróis da sua conta. Ordenados por poder por padrão.',
  switchHeroShort: 'Elenco',
};
