// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/gem.svg
import type { SVGProps } from "react";
const SvgGem = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path fill="currentColor" d="m12 2 8 7v2l-8 11-8-11V9zm0 5-5 3 5 9 5-9z" />
  </svg>
);
export default SvgGem;
