// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/key.svg
import type { SVGProps } from "react";
const SvgKey = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M8 4a5 5 0 1 0 3.2 8.8L14 16h3l1 4h3l-1-4 2-2-5.2-5.2A5 5 0 0 0 8 4m0 3a2 2 0 1 1 0 4 2 2 0 0 1 0-4"
    />
  </svg>
);
export default SvgKey;
