// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-5.svg
import type { SVGProps } from "react";
const SvgRarity5 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="m12 2 2.2 6.8H21l-5.5 4 2.1 6.8-5.6-3.2-5.6 3.2 2.1-6.8-5.5-4h6.8z"
    />
  </svg>
);
export default SvgRarity5;
