// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-2.svg
import type { SVGProps } from "react";
const SvgRarity2 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path fill="currentColor" d="m12 3 9 17H3zm0 6L6.5 19h11z" />
  </svg>
);
export default SvgRarity2;
