// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-1.svg
import type { SVGProps } from "react";
const SvgRarity1 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path fill="currentColor" d="M6 6h12v12H6zm3 3v6h6V9z" />
  </svg>
);
export default SvgRarity1;
