// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-0.svg
import type { SVGProps } from "react";
const SvgRarity0 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16m0 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10"
    />
  </svg>
);
export default SvgRarity0;
