// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-4.svg
import type { SVGProps } from "react";
const SvgRarity4 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="m12 2 4.5 2.6L20 4l-.6 5.5L24 12l-4.6 2.5.6 5.5-3.5-2.6L12 22l-4.5-4.6L4 20l.6-5.5L0 12l4.6-2.5L4 4l3.5 2.6z"
    />
  </svg>
);
export default SvgRarity4;
