// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/rarity-3.svg
import type { SVGProps } from "react";
const SvgRarity3 = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="m12 2 2.5 5.5L20 9l-4 4 1 6.5-5-2.5-5 2.5L8 13 4 9l5.5-1.5z"
    />
  </svg>
);
export default SvgRarity3;
