// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-bota.svg
import type { SVGProps } from "react";
const SvgSlotBota = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M8 6h4v4h6v2c0 3-2 6-6 6H8q-3 0-3-3V8c0-1 1-2 3-2m2 6v4h4c2 0 3-1 3-2h-7z"
    />
  </svg>
);
export default SvgSlotBota;
