// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-luva.svg
import type { SVGProps } from "react";
const SvgSlotLuva = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M9 4h2v5h2V3h2v6h2V5h2v8c0 2-2 4-5 4H9q-3 0-3-3V7q0-3 3-3"
    />
  </svg>
);
export default SvgSlotLuva;
