// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-elmo.svg
import type { SVGProps } from "react";
const SvgSlotElmo = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M4 14v-3c0-4 3.5-7 8-7s8 3 8 7v3h-2v-1c0-3-2.5-5-6-5s-6 2-6 5v1zm2 2h12v4H6z"
    />
  </svg>
);
export default SvgSlotElmo;
