// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-arma.svg
import type { SVGProps } from "react";
const SvgSlotArma = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="m12 2 2 6-2 2-2-2zm-1 8v10h2V10zM8 20h8v2H8z"
    />
  </svg>
);
export default SvgSlotArma;
