// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-peito.svg
import type { SVGProps } from "react";
const SvgSlotPeito = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M6 6h12l2 4v10H4V10zm2 4v8h8v-8zm4-2 1.5 2h-3z"
    />
  </svg>
);
export default SvgSlotPeito;
