// GENERATED by `pnpm --filter @bombfarm/ui icons:generate` — do not edit.
// Source: packages/ui/icons/game/slot-calca.svg
import type { SVGProps } from "react";
const SvgSlotCalca = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M7 4h10v6l-1 14h-3l-1-10-1 10H8L7 10zm2 2v3h6V6z"
    />
  </svg>
);
export default SvgSlotCalca;
